src/core/account_address.ts
tests/e2e/api/transaction_submission.test.ts
tests/unit/type_tag.test.ts

Disables a test, and fixes the type tag error message test
See CI

Fix broken tests

---

.prettierrc
src/api/account.ts
src/api/faucet.ts
src/api/general.ts
src/api/transaction.ts
src/api/transaction_submission.ts
src/client/core.ts
src/core/account.ts
src/core/account_address.ts
src/crypto/ed25519.ts
src/crypto/multi_ed25519.ts
src/internal/account.ts
src/internal/faucet.ts
src/internal/transaction.ts
src/transactions/authenticator/transaction.ts
src/transactions/transaction_builder/transaction_builder.ts
src/transactions/types.ts
src/types/generated/operations.ts
src/types/generated/types.ts
tests/e2e/api/transaction_submission.test.ts
tests/unit/account.test.ts
tests/unit/account_address.test.ts
tests/unit/authentication_key.test.ts
tests/unit/ed25519.test.ts
tests/unit/hex.test.ts
tests/unit/multi_ed25519.test.ts
tests/unit/secp256k1.test.ts
tests/unit/transaction_builder.test.ts
tests/unit/type_tag.test.ts

Run prettier and fix typos

---

.editorconfig
.gitattributes
CODEOWNERS
CONTRIBUTING.md
LICENSE
README.md

Updates the README to match the new SDK
N/A
N/A

[docs] Update README to match the new SDK

---

tests/e2e/api/transaction_submission.test.ts

Fix test name typo

---

src/api/transaction.ts
src/internal/account.ts
src/internal/transaction.ts

Specifically only memoize the common use case, and do not memoize ledger versions specifically.
This one is a hard one to test without inspecting the requests directly.  Once we have more E2E examples, I will watch and inspect the requests.

[api] Memoize gas estimation and module APIs

---

src/api/transaction.ts

Removes the duplicate that wasn't removed in the last revision of the last PR
CI

[api] Remove duplicate memoize on estimate gas price

---

.eslintignore
.eslintrc.js
.gitignore
.npmignore
.prettierignore
CODEOWNERS

This should add the users individually for now, and additionally prevent extra stuff from making it into builds.
CI, and I ran all commands individually

[ci] Update codeowners and ignore files

---

src/api/account.ts
src/internal/account.ts
tests/e2e/api/account.test.ts

1. Add lookupOriginalAccountAddress query
2. Add e2e test
Note: I will add additional e2e to this method when rotate key is ready.
pnpm fmt & pnpm test

[SDKv2] Add lookupOriginalAccountAddress query

---

src/transactions/types.ts
src/types/index.ts
tests/e2e/api/coin.test.ts
tests/unit/transaction_builder.test.ts

Small fixes
```typescript
pnpm jest
```

[Typos] Allow functions to accept AccountAddress and FixedBytes and fix types.ts typo

---

jest.config.js
tests/e2e/api/account.test.ts
tests/e2e/api/coin.test.ts
tests/e2e/api/faucet.test.ts
tests/e2e/api/transaction.test.ts
tests/e2e/api/transaction_builder.test.ts
tests/e2e/api/transaction_submission.test.ts
tests/unit/helper.ts
tests/unit/transaction_builder.test.ts

- Moves transaction builder tests
- Fixes some timing on tests
`pnpm unit-test` `pnpm e2e-test`

[tests] Fix CI tests to continue working

---

src/api/aptos.ts
src/api/collection.ts
src/internal/collection.ts
src/internal/queries/getCollectionData.graphql
src/types/generated/operations.ts
src/types/generated/queries.ts
src/types/generated/types.ts
src/types/indexer.ts
tests/e2e/api/collection.test.ts

Adds collection related queries to the SDK
pnpm test - tests against a random collection I selected from mainnet

Add collection queries

---

.prettierignore
package.json

This has fmt run on the generated graphql code.  This PR also chains fmt to run in the codegen script.
pnpm run indexer-codegen

Remove generated from prettierignore

---

src/core/crypto/secp256k1.ts
tests/e2e/transaction/transaction_submission.test.ts
tests/unit/helper.ts
tests/unit/secp256k1.test.ts

use sha3 with secp256k1 scheme

---

examples/typescript/package.json
examples/typescript/transfer_coin.ts

Similar to the transfer example, but instead using transferCoinTransaction
pnpm transfer_coin

Add transfer_coin example using transferCoinTransaction

---

tests/e2e/transaction/sign_transaction.test.ts
tests/e2e/transaction/transaction_simulation.test.ts
tests/e2e/transaction/transaction_submission.test.ts

I released a new CLI earlier that has the processor fixes for secpk stuff in it.
See that CI passes.

Stop skipping secpk tests

---

package.json
src/version.ts

update package name and version

---

README.md

[docs] Update NPM badges

---

src/api/event.ts

Remove unused pagination arg in getAccountEventsByCreationNumber

---

src/api/aptos.ts
src/api/fungible_asset.ts
src/internal/fungible_asset.ts
src/internal/queries/getCurrentFungibleAssetBalances.graphql
src/types/generated/operations.ts
src/types/generated/queries.ts
src/types/indexer.ts
tests/e2e/api/fungible_asset.test.ts

Add api query - getCurrentFungibleAssetBalances
pnpm test
pnpm fmt

Add api getCurrentFungibleAssetBalances

---

README.md

Fixes some typos and adds a little clarity for some examples that were mixing addresses and accounts.

[docs] Update readme for typos and more clarity

---

src/bcs/serializer.ts
src/transactions/instances/transactionPayload.ts
src/transactions/transaction_builder/transaction_builder.ts
src/transactions/types.ts

Ensure that types are permissive when they should be.  e.g.
- Bytecode should be allowed to be bytes
- BigInt inputs should be allowed to be numbers (skip string inputs, though we could allow it for compatibility if we care)
CI

[types] Use appropriate type when necessary

---

tests/e2e/client/aptosRequest.test.ts

Add missing tests for `aptosRequest` function and increase test coverage

Add tests for `aptosRequest`

---

src/internal/digitalAsset.ts

Since we agreed to not throw error. see [thread](https://aptos-org.slack.com/archives/C04339KQNUC/p1698185113524819) for reference 
Lets remove error throwing if data not found from graphql query
pnpm test

[Easy] Do not throw if collection not found

---

src/api/transactionSubmission.ts
src/bcs/serializable/moveStructs.ts
src/internal/transactionSubmission.ts
src/transactions/types.ts
tests/e2e/transaction/helper.ts
tests/e2e/transaction/transactionArguments.test.ts
tests/e2e/transaction/transactionBuilder.test.ts
tests/e2e/transaction/transactionSubmission.test.ts
tests/unit/bcsHelper.test.ts

These are all issues I ran into building the Remote ABI work, which caused some other issues.  So, I've separated them out due to dealing with merge conflicts.
CI

[tests/types] Various improvements

---

src/api/faucet.ts
src/internal/faucet.ts

Forgot to propagate the WaitForTransactionOptions to Faucet.
pnpm test

update faucet to include WaitForTransactionOptions

---

README.md

update readme to use privateKey and not hex string

---

examples/typescript/swap.ts

1. Use toStringLong() for address
2. update func name to use correct format after fix

[easy] fix swap

---

src/core/accountAddress.ts
tests/e2e/transaction/helper.ts

- Added "0x" to the return type of some methods from AccountAddress
- Leveraging generic signature to simplify test helper (pair programming with @xbtmatt 
Unit and e2e tests are passing

[tests] Removed forced types discrimination

---

src/core/account.ts
src/internal/account.ts
tests/unit/account.test.ts

Rename `Account.fromPrivateKey` to `Account.fromPrivateKeyAndAddress`

---

src/core/authenticationKey.ts
tests/unit/authenticationKey.test.ts

Update AuthKey to extend from Serializable.
pnpm test

Update AuthenticationKey to extend from Serializable

---

src/client/core.ts

This fixes the API error output to print as JSON.  Before, it would always say `BadRequest`, but now it will return a proper error
I tested this / it was actually for a different PR I had, though it's taking a while to get it in 
e.g.
```
{"message":"Failed to deserialize input into SignedTransaction: DeserializationError with Secp256k1EcdsaPublicKey","error_code":"invalid_input","vm_error_code":null}
AptosApiError: {"message":"Failed to deserialize input into SignedTransaction: DeserializationError with Secp256k1EcdsaPublicKey","error_code":"invalid_input","vm_error_code":null}
at aptosRequest (/opt/git/typescript-sdk/src/client/core.ts:112:9)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at submitTransaction …
```

[error] Fix error output to show JSON output

---

.eslintrc.js
.github/actions/run-examples/action.yaml
.github/workflows/run-examples.yaml
examples/javascript/package.json
examples/javascript/pnpm-lock.yaml
examples/javascript/simple_sponsored_transaction.js
examples/javascript/simple_transfer.js
examples/typescript/.npmrc
examples/typescript/custom_client.ts
examples/typescript/mint_nft.ts
examples/typescript/multi_agent_transfer.ts
examples/typescript/package.json
examples/typescript/pnpm-lock.yaml
examples/typescript/publish_package_from_filepath.ts
examples/typescript/simple_sponsored_transaction.ts
examples/typescript/simple_transfer.ts
examples/typescript/swap.ts
examples/typescript/transfer_coin.ts
package.json
src/utils/apiEndpoints.ts

This sets up all examples to run in one command (except the two that are broken).
Additionally, linting now works properly on the examples as well (and has been cleaned up).
All running examples worked correctly for me when running `pnpm test`, this PR tests the CI of running the examples.

[examples] Add examples to the CI, and ensure linting and formatting work correctly

---

src/core/account.ts
src/core/crypto/ed25519.ts
src/core/crypto/secp256k1.ts
tests/unit/account.test.ts
tests/unit/ed25519.test.ts
tests/unit/hdKey.test.ts
tests/unit/secp256k1.test.ts

following https://github.com/aptos-labs/aptos-ts-sdk/pull/146#pullrequestreview-1707312446
1. Remove KeyType enum
2. Add hd tests
3. Making @alinush happy
pnpm test

Add tests for hd keys and code improvements 

---

src/transactions/transactionBuilder/remoteAbi.ts
src/transactions/typeTag/index.ts
tests/e2e/api/coin.test.ts
tests/unit/typeTag.test.ts

I think there are more. I think there is more, will fix it as I find them.

[Easy] Clean up typetag snake case to camelcase

---

package.json
src/transactions/types.ts
tsup.config.ts

- `typeArguments` to accept `Array<TypeTag | string>`
- bundle esm build, https://aptos-org.slack.com/archives/C05NLAKJM9U/p1699306248561609?thread_ts=1699046504.394959&cid=C05NLAKJM9U

Some fixes

---

CHANGELOG.md
package.json
src/core/account.ts

Bump version

---

src/index.ts
src/utils/index.ts
tests/e2e/transaction/transactionSubmission.test.ts

Export api endpoints and consts files from utils folder

---

examples/typescript/transfer_coin.ts
src/internal/coin.ts

Updates to transfer coin example and function following https://github.com/aptos-labs/aptos-core/pull/11125

Updates to transfer coin example and function

---

.eslintrc.js
CHANGELOG.md
examples/typescript/batch_funds.ts
examples/typescript/batch_mint.ts
src/api/transactionSubmission.ts
src/index.ts
src/internal/transactionSubmission.ts
src/transactions/management/accountSequenceNumber.ts
src/transactions/management/asyncQueue.ts
src/transactions/management/index.ts
src/transactions/management/transactionWorker.ts
tests/e2e/transactionManagement/accountSequenceNumber.test.ts
tests/e2e/transactionManagement/asyncQueue.test.ts
tests/e2e/transactionManagement/transactionWorker.test.ts

This PR ports over the existing sdk v1 transaction management and makes adjustments to use it in the new sdk.
Also, adds 2 examples on how to use the worker to fund multiple account and mint multiple tokens.
pnpm test

Introduce transaction management layer

---

.github/actions/run-lint/action.yaml
CHANGELOG.md
CONTRIBUTING.md
package.json
scripts/checkVersion.sh
scripts/generateDocs.sh
scripts/updateVersion.sh

Doc build and version updates should now automatically add new ones when run, which will be a lot simpler.
Ran locally

[automation] Improve build

---

examples/typescript/package.json
examples/typescript/your_fungible_asset.ts

Fix your fungible asset example

Fix your fungible asset example

---

CHANGELOG.md
examples/typescript/external_signing.ts
src/api/ans.ts
src/api/coin.ts
src/api/digitalAsset.ts
src/api/fungibleAsset.ts
src/api/transaction.ts
src/api/transactionSubmission/build.ts
src/internal/ans.ts
src/internal/coin.ts
src/internal/digitalAsset.ts
src/internal/fungibleAsset.ts
src/internal/transactionSubmission.ts
src/transactions/management/transactionWorker.ts
src/transactions/transactionBuilder/transactionBuilder.ts
src/transactions/types.ts

Following https://github.com/aptos-labs/aptos-ts-sdk/pull/226 , rename type

Rename `SingleSignerTransaction` type to `SimpleTransaction`

---

scripts/generateDocs.sh

[docs] Change default generation tag to Stable

---

CHANGELOG.md
examples/typescript-esm/multisig_v2.ts
examples/typescript-esm/package.json
examples/typescript-esm/pnpm-lock.yaml
src/transactions/instances/transactionPayload.ts
src/transactions/transactionBuilder/transactionBuilder.ts
src/transactions/types.ts
tests/e2e/api/staking.test.ts
tests/e2e/transaction/generateTransaction.test.ts
tests/e2e/transaction/transactionBuilder.test.ts

This PR adds a multisig example (legacy sdk reference [example](https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/examples/typescript/multisig_account.ts))
While working on it, I noticed some gaps in our current SDK.
- ABI parser support for a `TransactionPayloadMultiSig` without a `MultiSigTransactionPayload` 
- Offer a framework around building and interacting with multisig transactions with the SDK.
- pnpm run test
- example output
```
owner1: 0xcea337802e090d160d0fa6952c4644f99af5fdbf2dd14ed205e09189872b3d00
owner2: 0x43a6e5e7e5551abae94d7362fc37bd2ca6d2d9b3bed4a4e23c9c958500b75bd4
owner3: 0x86efd860ec4680c7938226080f48b9b8465ffe9fec54b396ffa764911e28db91
Setting up a 2-of-3 multisig account...
Multisig Account Address: …
```

Add a multisig example

---

CODEOWNERS

Update codewoners file

---

README.md

Link didn't work, fixed to the new link

[README] Fix SDK documentation link

---

CHANGELOG.md
src/internal/event.ts

Add optional `options`  param to `getAccountEventsByCreationNumber`  query for paginations and order by

---

docs/@aptos-labs/.nojekyll
docs/@aptos-labs/index.html
docs/@aptos-labs/ts-sdk-latest/.nojekyll
docs/@aptos-labs/ts-sdk-latest/index.html

Try number 2, using HTML direct redirects https://dev.to/steveblue/setup-a-redirect-on-github-pages-1ok7

[docs] Change jekyll specific redirects to regular HTML redirects

---

docs/404.html
docs/@aptos-labs/index.md
docs/@aptos-labs/ts-sdk-latest/index.md
docs/Gemfile
docs/Gemfile.lock
docs/_config.yml
docs/index.md

For some reason, this initially worked without the plugin, but now it needs it.  The plugin fixes the redirects.  Check here https://gregnazario.github.io/aptos-ts-sdk
Tested:
https://gregnazario.github.io/aptos-ts-sdk/@aptos-labs
https://gregnazario.github.io/aptos-ts-sdk/@aptos-labs/ts-sdk-latest
https://gregnazario.github.io/aptos-ts-sdk/not-a-page

[docs] Add proper jekyll plugins for redirects

---

examples/typescript/move/claims/Move.toml
examples/typescript/move/claims/sources/claims.move
examples/typescript/package.json
examples/typescript/sign_struct.ts

As requested a few times from members of the community, an example on how to sign a struct on-chain and prove that it's successful with an e2e test.
Example worked fully as expected locally

[examples] Make a TypeScript example for offchain struct signing

---

CHANGELOG.md
src/api/digitalAsset.ts
src/internal/digitalAsset.ts
tests/e2e/api/collection.test.ts

Close https://github.com/aptos-labs/aptos-ts-sdk/issues/274
Uint test.

Add get collection by ID API

---

CHANGELOG.md

We forgot to add this change to CHANGELOG https://github.com/aptos-labs/aptos-ts-sdk/pull/302

update CHANGELOG with latest sdk change

---

examples/typescript/asset_uploader.ts
src/plugins/assetUploader/README.md

add detailed examples on how to use this asset uploader.
verified working
```
Starting fund node
fund response {
reward: '{"gasUnitPrice":100,"maxGasAmount":12}',
target: '0xfa3e389d045e057145e29f544f9809c28399f8167e0e45fd157084858dda8a0f',
quantity: '1000000',
id: '0x61ae083c05203ab7393eba35e2bca719c5768569e05ab0f87484c7bef400088e'
}
Collection Media URL: https://arweave.net/0C8IiWUA_hQUXNIuPCsV1Ndu2reW7J5QkzLfHH4zsz8
Collection metadata json URL: https://arweave.net/YqYjZAkd91PEhy6CiYdfC_swCNTJ5K5curMGW5m2lrg
Token media URL folder: https://arweave.net/2NhlIkaemZNc5G5gcumMbmYkCvRoQaeFTUyylZXXfOw
Token metadata json URL folder: https://arweave.net/n_8e-WepY_nfrBi2lkDu5fPyPRumucVm7HDeAkkLiT4
```

[TMP] update asset uploader example to make it actually working

---

src/transactions/transactionBuilder/transactionBuilder.ts

Handling automatic authenticator generation for keyless transaction simulation

Fixed keyless simulation

---

src/transactions/transactionBuilder/remoteAbi.ts
tsup.config.ts

fix cjs error

---

CHANGELOG.md
src/api/ans.ts
src/internal/ans.ts
tests/e2e/ans/ans.test.ts

Resolves https://github.com/aptos-labs/aptos-ts-sdk/issues/311

Change ANS queries return types

---

CHANGELOG.md
src/core/account/utils/address.ts
tests/unit/address.test.ts

There is no corresponding method when you need to calculate the resource account in advance offline.
https://explorer.aptoslabs.com/account/0x41e724e1d4fce6472ffcb5c9886770893eb49489e3f531d0aa97bf951e66d70c/modules/view/create_resource/create_resource?network=testnet
close #353

[Feature Request] Add resource account address calculation

---

src/index.ts

Revert export cli

---

src/internal/account.ts

Clean code from deprecated functions

---

CHANGELOG.md
package.json
pnpm-lock.yaml

Following https://aptos-org.slack.com/archives/C06KSKYNN7R/p1714309654711519

Use `@aptos-labs/aptos-cli` as a regular dependency

---

CHANGELOG.md
src/transactions/instances/index.ts

Export MultiAgentTransaction class

---

CHANGELOG.md
examples/typescript/package.json

- adding changelog for https://github.com/aptos-labs/aptos-ts-sdk/pull/387
- adding the examples to run test when push a PR
see if the examples are run when submitting

adding example running and changelog

---

examples/typescript/your_coin.ts
examples/typescript/your_fungible_asset.ts

while going through Aptos Learn

Clean up some examples typos

---

CHANGELOG.md
examples/typescript/localNode.ts
src/cli/index.ts
src/cli/move.ts

To enhance the SDK, and to support future work in another area, this PR adds support for commonly used CLI commands
- aptos init
- aptos move compile
- aptos move test
- aptos move publish

Add support for cli move commands

---

CHANGELOG.md
src/internal/ans.ts
src/utils/apiEndpoints.ts
tests/unit/aptosConfig.test.ts

Randomnet is done

---

examples/typescript-esm/multisig_v2.ts

Add simulation step to `multisig_v2` example

---

CHANGELOG.md
examples/typescript/pnpm-lock.yaml
package.json
pnpm-lock.yaml

Upgrade aptos-cli package to version 0.1.7

---

CHANGELOG.md
package.json
pnpm-lock.yaml

Upgrade `aptos-cli` package dependency

---

CHANGELOG.md
examples/typescript/localNode.ts
src/cli/localNode.ts
src/cli/move.ts

Fix CLI scripts to be OS compatible with Mac, Linux and Windows

Support windows on CLI commands

---

.github/ISSUE_TEMPLATE/config.yml

[github] Change questions section to mention aptos developer discussions

---

CHANGELOG.md
src/internal/queries/getFungibleAssetMetadata.graphql
src/types/generated/operations.ts
src/types/generated/queries.ts
src/types/generated/types.ts
tests/e2e/api/digitalAsset.test.ts
tests/e2e/api/fungibleAsset.test.ts

Add `supply_v2` and `maximum_v2` scheme fields to `getFungibleAssetMetadata` query

Generate Fungible Asset indexer query properties

---

CHANGELOG.md
src/transactions/transactionBuilder/transactionBuilder.ts

This sends a 'null' signature of Keyless type instead of Ed25519

Fix keyless transaction simulation

---

CHANGELOG.md
src/cli/move.ts

Fix for https://github.com/aptos-labs/aptos-ts-sdk/pull/421

Fix named addresses fix

---

CHANGELOG.md
src/api/fungibleAsset.ts
tests/e2e/api/fungibleAsset.test.ts

Add API function to fetch fungible asset metadata by the creator address

---

CHANGELOG.md
src/cli/move.ts

Always fetch latest main in cli

---

CHANGELOG.md
src/internal/event.ts
tests/e2e/api/event.test.ts

Pagination arguments are not being passed correctly

[Hot Fix] Respect pagination arguments on  queries

---

CHANGELOG.md
src/core/index.ts

Export Helper Functions
- createObjectAddress
- createResourceAddress
- createTokenAddress

Export Several Helper Functions for Address Calculation

---

package.json
pnpm-lock.yaml
src/plugins/assetUploader/index.ts
src/plugins/assetUploader/irys.ts
src/plugins/assetUploader/types.ts

add getprice to estimate irys upload cost
https://docs.irys.xyz/developer-docs/irys-sdk/api/getPrice

add getprice to estimate irys upload cost

---

pnpm-lock.yaml
src/plugins/assetUploader/index.ts
src/plugins/assetUploader/irys.ts
src/plugins/assetUploader/types.ts

verified working with local npm link
```
const estimatedCost = await assetUploader.estimateFolderPrice({account,
folderInfo: fileSizes,
});
```

fix estimateFolderPrice to take account

---

pnpm-lock.yaml
src/plugins/assetUploader/index.ts
src/plugins/assetUploader/irys.ts
src/plugins/assetUploader/types.ts

verified working using npm link
`const irysBalance = await assetUploader.getLoadedBalance({account});`

add getLoadedBalance

---

CHANGELOG.md
src/types/index.ts

Add BlockEpilogue transaction to ts SDK

Adding BlockEpilogue transaction to ts

---

.github/actions/run-build/action.yaml
.github/actions/run-check-version/action.yaml
.github/actions/run-examples/action.yaml
.github/actions/run-fmt/action.yaml
.github/actions/run-lint/action.yaml
.github/actions/run-tests/action.yaml

Fixes the issue described in https://github.com/pnpm/action-setup/issues/135, which is breaking our CI.
See CI.
N/A

Update pnpm/action-setup to v4

---

CHANGELOG.md
src/api/faucet.ts

https://aptos-org.slack.com/archives/C05NLAKJM9U/p1720643858300339

Have fundAccount to wait for fungible_asset_processor indexer processor

---

CHANGELOG.md
examples/typescript/local_node.ts
src/cli/move.ts

Support optional `extraArguments` property for the cli Move commands

---

CHANGELOG.md
package.json
pnpm-lock.yaml

Upgrade aptos-cli dependency version to 0.2.0

---

package.json

update to 1.9.1-tmp.3

---

CHANGELOG.md
src/types/generated/operations.ts
src/types/generated/types.ts

Update indexer GQL schema

---

CHANGELOG.md
src/utils/helpers.ts
src/utils/index.ts
tests/unit/conversion.test.ts

Add helper conversion methods

---

CHANGELOG.md
package.json
pnpm-lock.yaml

bump aptos-client to version 0.1.1

---

CHANGELOG.md
src/cli/move.ts

[Hot Fix] Change regex to find object address when using  move function

---

examples/typescript-esm/package.json
examples/typescript/local_node.ts
tests/e2e/ans/publishANSContracts.ts

This should remove warnings from linter, as well as unblock CI

Cleanup sdk tests

---

src/account/KeylessAccountCommon.ts

This provides immediate guidance for developers who encounter this issue

Update proof not found error message

---

src/account/EphemeralKeyPair.ts
src/account/FederatedKeylessAccount.ts
src/account/KeylessAccount.ts
src/core/crypto/index.ts
src/core/crypto/poseidon.ts
tests/unit/poseidon.test.ts

Allow for this code to be used
Already exists

Export the poseidon code in /core/crypto

---

src/account/FederatedKeylessAccount.ts
src/account/KeylessAccount.ts
src/account/KeylessAccountCommon.ts
src/core/crypto/keyless.ts
src/internal/keyless.ts

- Fix some comments
- Fix some names
- Avoid ! when type inferrence and error handling are preferred

[keyless] Some cleanups

---

README.md

Update README.md broken links

---

CHANGELOG.md
examples/typescript/.gitignore
examples/typescript/local_node.ts
src/cli/localNode.ts
src/cli/move.ts

Add `showStdout` optional property to `Move` and `LocalNode` classes to control the output of the CLI commands

Add `showStdout` optional property to `Move` and `LocalNode`  classes

---

CHANGELOG.md
src/bcs/serializer.ts
src/core/authenticationKey.ts
src/core/crypto/ephemeral.ts
src/core/crypto/federatedKeyless.ts
src/core/crypto/keyless.ts
src/core/crypto/multiKey.ts
src/core/crypto/proof.ts
src/core/crypto/publicKey.ts
src/core/crypto/signature.ts

Just to clean up some code
Current tests keep passing

Add default implementations for toString for Serializable classes

---

src/cli/localNode.ts

Following https://github.com/aptos-labs/aptos-core/pull/15005 we are now printing correct regular/error logs

Do not ignore stderr when stdout is disabled

---

CHANGELOG.md
package.json
pnpm-lock.yaml

Tested with the `local_node` example

Bump aptos-cli dep to version 1.0.1

---

src/api/keyless.ts
src/internal/keyless.ts

Adds the missing `options` param

Add the ability to set options when creating a jwk_update txn

---

.github/PULL_REQUEST_TEMPLATE.md

Add update changelog step to pull request template

---

CHANGELOG.md
package.json
pnpm-lock.yaml

Bump aptos-cli dep to 1.0.2

---

tests/e2e/api/event.test.ts

[tests] Disable e2e module events retrieval test

---

package.json
pnpm-lock.yaml
src/transactions/script-composer/index.ts

[scriptComposer] Fix warning caused by init method

---

CHANGELOG.md
src/internal/keyless.ts
src/utils/const.ts
tests/e2e/api/keyless.test.ts

This allows for installing the JWKs needed for firebase to be used with keyless.
e2e test added

Add support for firebase JWK updates

---

projects/gas-station/README.md
projects/gas-station/package.json
projects/gas-station/pnpm-lock.yaml
projects/gas-station/src/client.ts
projects/gas-station/src/server.ts
projects/gas-station/tsconfig.json

Gas station example, running express server

Gas station example

---

src/internal/permissions.ts
src/types/permissions.ts
tests/e2e/transaction/delegationPermissions.test.ts

Normalizes amount to bigint

---

examples/typescript-esm/sponsored_transactions/simple_sponsored_transaction.ts
examples/typescript/external_signing.ts
examples/typescript/federated_keyless.ts
examples/typescript/move/claims/sources/claims.move

examples/typescript-esm/sponsored_transactions/simple_sponsored_transaction.ts
with sponsor - with a sponsor
examples/typescript/external_signing.ts
access - accesses
examples/typescript/federated_keyless.ts
tokens" - tokens'
examples/typescript/move/claims/sources/claims.move
onchcain - onchain

fix spelling issues 

---

CHANGELOG.md
examples/typescript/package.json
examples/typescript/view_bcs.ts
package.json
pnpm-lock.yaml
src/api/aptos.ts
src/api/aptosConfig.ts
src/api/experimental.ts
src/client/core.ts
src/client/get.ts
src/client/post.ts
src/core/hex.ts
src/internal/experimental.ts
src/internal/view.ts
src/types/types.ts
tests/e2e/api/general.test.ts

This is experimental for now, and will be moved into the main SDK at a later time.
Dependent on https://github.com/aptos-labs/aptos-client/pull/2

[view] Add ability to get BCS output from view functions

---

projects/gas-station/package.json
projects/gas-station/pnpm-lock.yaml

Updates gas station dependencies
pnpm build

[deps] Update gas station deps

---

src/api/general.ts

Fix example code in `queryIndexer` comments.
None
None

Fix the example in comments

---

CHANGELOG.md
examples/javascript/package.json
examples/javascript/pnpm-lock.yaml
examples/typescript-esm/package.json
examples/typescript-esm/pnpm-lock.yaml
examples/typescript/package.json
examples/typescript/pnpm-lock.yaml
package.json
pnpm-lock.yaml
projects/gas-station/package.json
projects/gas-station/pnpm-lock.yaml

[deps] Upgrade dependencies for examples for security issues

---

CHANGELOG.md
src/core/crypto/index.ts

Export the `abstraction.ts` file

---

CHANGELOG.md
package.json
pnpm-lock.yaml

Updates babel dependencies for security audit checks

[deps] Update babel dependencies

---

examples/typescript/multi_agent_transfer.ts
examples/typescript/publish_package_from_filepath.ts

Fix multi agent transfer example test

---

examples/typescript/move/facoin/sources/fa_coin.move
examples/typescript/package.json
examples/typescript/pnpm-lock.yaml
examples/typescript/your_fungible_asset.ts

Your First Fungible Asset Guide was not in sync with the FA_coin module and the script.

Update your first fungible asset

---

CHANGELOG.md
src/api/account.ts

[bugfix] Fix view function .at(0)

---

confidential-assets/package.json
confidential-assets/pnpm-lock.yaml
examples/javascript/package.json
examples/javascript/pnpm-lock.yaml
examples/typescript-esm/package.json
examples/typescript-esm/pnpm-lock.yaml
examples/typescript/package.json
examples/typescript/pnpm-lock.yaml
package.json
pnpm-lock.yaml
projects/gas-station/package.json
projects/gas-station/pnpm-lock.yaml

Removes ts-node everywhere, replaces it with tsx when necessary.
Also, fixes some dependency updates, should all be dev dependency based or in examples.

[deps] update dependencies for TSX, gas station, confidential assets

---

CHANGELOG.md
src/api/account.ts
src/internal/account.ts
tests/e2e/api/account.test.ts

[account] Add Get Balance Function

---

CHANGELOG.md
src/internal/ans.ts
src/utils/apiEndpoints.ts

> [!WARNING]  
> Do NOT merge until `shelbydevnet` -> `shelbynet` network name changes are complete

[ts-sdk] Add shelbynet endpoints
