.github/actions/run-build/action.yaml, .github/actions/run-fmt/action.yaml, .github/actions/run-lint/action.yaml, .github/actions/run-unit-tests/action.yaml, .github/workflows/run-build.yaml, .github/workflows/run-fmt.yaml, .github/workflows/run-lint.yaml, .github/workflows/run-unit-tests.yaml, package.json
Adds auto format and lint checking, as well as build checking in parallel with the E2E testing
We'll see through this PR
=> [ci] Add auto lint and format checking

tests/e2e/api/account.test.ts, tests/e2e/api/general.test.ts, tests/e2e/api/transaction.test.ts, tests/e2e/api/transaction_submission.test.ts, tests/unit/account.test.ts, tests/unit/account_address.test.ts, tests/unit/aptos_config.test.ts, tests/unit/authentication_key.test.ts, tests/unit/bcs-helper.test.ts, tests/unit/deserializer.test.ts, tests/unit/ed25519.test.ts, tests/unit/hex.test.ts, tests/unit/multi_ed25519.test.ts, tests/unit/secp256k1.test.ts, tests/unit/serializer.test.ts, tests/unit/transaction_builder.test.ts, tests/unit/type_tag.test.ts
We export many of our types and functions up to the top level, which is where all of them should be in the end for the SDK. This is a good way to view the user experience when using the SDK.
```
pnpm fmt && pnpm lint && pnpm test
```
=> [tests] Combine and shorten imports where applicable

src/api/transaction_submission.ts, src/client/core.ts, src/client/get.ts, src/client/post.ts, src/client/types.ts, src/internal/transaction_submission.ts, src/transactions/transaction_builder/transaction_builder.ts, src/types/index.ts, src/utils/const.ts, tests/unit/transaction_builder.test.ts
Just realized that previous PR was not completely full as we need to have those pure functions internally that handles the logic.  
This PR conforms to the sdk design in a way that everything in `api/` folder is a user facing interface functions and those in `internal/` folder are responsible on the actual logic.
more info https://github.com/aptos-labs/aptos-ts-sdk/pull/11/files#diff-a5a44d0986e0254ae62cd623aeaac609a288c9b2eabe5c741fd5b4a4f350a3ddR2
`pnpm jest`
=> Add internal transaction submission file

src/api/transaction.ts, tests/e2e/api/transaction.test.ts
Add missing transaction query test, a better test framework to come after
https://aptos-org.slack.com/archives/C04339KQNUC/p1697063710300629
```
transaction api
✓ it queries for the network estimated gas price (40 ms)
✓ returns true when transaction is pending (739 ms)
fetch transaction queries
✓ it queries for transactions on the chain (34 ms)
✓ it queries for transactions by version (10 ms)
✓ it queries for transactions by hash (9 ms)
```
=> Add transaction query tests

src/bcs/index.ts, src/index.ts
As part of the external examples, adding the exports as the unit tests can't catch that these exports aren't visible outside
I have two example PRs that are upcoming and dependent on this
=> [exports] Add more exports to allow using the SDK

tests/e2e/api/account.test.ts
Add missing account query tests, a better test framework to come after
https://aptos-org.slack.com/archives/C04339KQNUC/p1697063710300629
```
✓ it fetches account transactions (912 ms)
✓ it fetches account transactions (1129 ms)
✓ it fetches account coins data (641 ms)
✓ it fetches account coins count (835 ms)
```
=> Add account query tests

src/api/account.ts, src/api/aptos.ts, src/api/coin.ts, src/api/transaction_submission.ts, src/internal/coin.ts, tests/e2e/api/coin.test.ts
Adds a built in `transferCoinTransaction` to `Aptos`.
```
const aptos = new Aptos()
const transaction = await aptos.transferCoinTransaction()
```
This function generates a transfer coin transaction that can be simulated and/or sign and submit. That is to have support for wallets and developers.
In addition, added a `signAndSubmitTransaction` API function for a single signer transaction to ease the user submission flow
```
coin
✓ it generates a transfer coin transaction with AptosCoin coin type (802 ms)
✓ it generates a transfer coin transaction with a custom coin type (481 ms)
✓ it transfers APT coin aomunt from sender to recipient (1609 ms)
```
=> Add built-in `transferCoinTransaction()` function

.github/actions/run-e2e-tests/action.yaml
This will let us have E2E tests that rely on the indexer API being present.
See that CI passes.
=> Run the indexer API with the local testnet in the E2E tests

src/transactions/typeTag/typeTag.ts, tests/unit/type_tag.test.ts
The previous code would double consume a nested type.  For example:
`A<B<C>>` Would consume `A<B<C>` and then skip over the last `>` which then made it crash.
`pnpm test`
Mirror of https://github.com/aptos-labs/aptos-core/pull/10484
=> [typeTag] Fix nested struct tag consumption

.eslintrc.js
This adds some more lints to prevent some bad practices like `require()` and providing `index.js`.
```
pnpm lint
```
=> [eslint] Check for possible ESM compatibility issues

tests/e2e/api/account.test.ts
A unit test had a typo because of a missing 0, added a const and used it to avoid typo issue and magic numbers. Also removed other various typos
`pnpm test` now succeeds
=> [Tests] Fixing broken unit test due to a missing zero, and various other typos

.github/actions/run-e2e-tests/action.yaml
This works until we come up with a solution in the CLI. Nothing running on the ports we kill is essential to the functioning of the runner.
CI.
=> Show local testnet logs on failure, free up needed ports

src/utils/apiEndpoints.ts, tests/e2e/api/account.test.ts, tests/e2e/api/coin.test.ts, tests/e2e/api/transaction_submission.test.ts, tests/unit/aptos_config.test.ts, tests/unit/transaction_builder.test.ts
Change tall tests to use local network.
@banool do we need docker in CI?
There is a latency chance when querying indexer right after we submit a transaction, therefore adding `sleep(100)` - can think about a different approach for our test framework we want to have or in a following PR.
```
PASS  tests/unit/account.test.ts
PASS  tests/unit/ed25519.test.ts
PASS  tests/e2e/api/general.test.ts
PASS  tests/e2e/api/faucet.test.ts
PASS  tests/unit/memoize.test.ts
PASS  tests/unit/secp256k1.test.ts
PASS  tests/unit/bcs-helper.test.ts
PASS  tests/unit/aptos_config.test.ts
PASS  tests/unit/multi_ed25519.test.ts
PASS  tests/unit/type_tag.test.ts
PASS  tests/unit/account_address.test.ts
PASS  tests/unit/serializer.test.ts
PASS  tests/unit/script_transaction_arguments.test.ts
PASS …
```
=> Use local network with tests

package.json, pnpm-lock.yaml, scripts/generateDocs.sh
Now we can generate documentation, to prevent churn at this moment, I'm still hiding docs via .gitignore so they aren't added.  We will be able to use GitHub pages directly to publish the TS Docs
`pnpm doc`
```
ls docs/aptos-2.0.0 
assets       classes      enums        functions    index.html   interfaces   modules.html types        variables
```
=> [docs] Add docs generation to the npm scripts

.github/actionlint.yaml, .github/actions/run-e2e-tests/action.yaml, .github/workflows/run-e2e-tests.yaml
The GH provided runners have a bunch of stuff running on them that the local testnet collides with. This doesn't happen with our own runners.
I reran the workflow 5 times and it worked every time.
=> Run E2E tests on high-perf-docker

src/core/account.ts, tests/e2e/api/account.test.ts, tests/e2e/api/coin.test.ts, tests/e2e/api/faucet.test.ts, tests/e2e/api/transaction.test.ts, tests/e2e/api/transaction_builder.test.ts, tests/e2e/api/transaction_submission.test.ts, tests/unit/account.test.ts
Default `Account.generate` to `ES25519` scheme with on optional scheme input argument.
pnpm jest
=> Default to ed25519 on account creation

src/api/general.ts, src/internal/general.ts, src/internal/queries/getChainTopUserTransactions.graphql, src/types/generated/operations.ts, src/types/generated/queries.ts, src/types/indexer.ts, tests/e2e/api/general.test.ts
Add the query getChainTopUserTransactions and e2e test
pnpm test
pnpm fmt
=> Add getChainTopUserTransactions.graphql

src/api/aptos.ts, src/api/event.ts, src/internal/event.ts, src/internal/queries/getEventsByCreationNumber.graphql, src/types/generated/operations.ts, src/types/generated/queries.ts, src/types/indexer.ts, tests/e2e/api/event.test.ts
1. Add Indexer query - getEventsByCreationNumber
2. e2e
pnpm fmt
=> Add getEventsByCreationNumber

src/bcs/serializable/fixed-bytes.ts, src/bcs/serializable/move-structs.ts, src/bcs/serializer.ts, src/core/account.ts, src/core/authentication_key.ts, src/core/crypto/asymmetric_crypto.ts, src/core/crypto/ed25519.ts, src/core/crypto/multi_ed25519.ts, src/core/crypto/secp256k1.ts, src/core/hex.ts, src/internal/account.ts, src/internal/collection.ts, src/internal/staking.ts, src/transactions/transaction_builder/transaction_builder.ts, tests/e2e/api/transaction_builder.test.ts, tests/unit/account.test.ts, tests/unit/authentication_key.test.ts, tests/unit/ed25519.test.ts, tests/unit/hex.test.ts, tests/unit/multi_ed25519.test.ts, tests/unit/secp256k1.test.ts
For functions that clearly are single param, don't use object as params.
pnpm test
=> Refactor object as params for single param funcs

src/api/account.ts, src/api/coin.ts, src/api/collection.ts, src/api/event.ts, src/api/faucet.ts, src/api/general.ts, src/api/staking.ts, src/api/transaction.ts, src/api/transaction_submission.ts
Fixes a bad code pattern that was previously used to avoid a lint.
```
async outer(): Promise<> {
const ret = await inner();
return ret;
}
```
is now the below because the inner one doesn't have to be awaited (just passed back out)
```
async outer(): Promise<> {
return inner();
}
```
CI
=> [lint] Fixes a bad code pattern

src/core/account.ts, src/index.ts, src/utils/hdKey.ts, tests/unit/account.test.ts, tests/unit/hdKey.test.ts, tests/unit/helper.ts
Cleans up and adds proper testing for seed phrase derivation.  This also opens up the path for
derivation of other keys.
Additionally, this removes `isValidPath` from the Account class, as it doesn't really belong there, but instead it is separate on it's own.
Added testing for valid and invalid seed phrases, ensured that derivation changes based on the path, and that the key derivation is correct.
=> [hdkey] Consolidate and add testing for seed phrase derivation

src/api/general.ts, tests/e2e/api/general.test.ts
If a view function returns a tuple, it will return multiple values. This changes the assumption that there is only one return value.
Adjusted the existing test, but need a new contract to show a view function that has more than one return value
=> [api] Fix view functions to return multiple values

src/api/general.ts, src/internal/general.ts, src/internal/queries/getProcessorStatus.graphql, src/internal/transaction.ts, src/types/generated/operations.ts, src/types/generated/queries.ts, src/types/indexer.ts, tests/e2e/api/account.test.ts, tests/e2e/api/coin.test.ts, tests/e2e/api/event.test.ts, tests/unit/helper.ts
Update waitForTransaction to include and wait for indexer sync
1. Add `getProcessorStatus` to get the latest success version from indexer
2. Add method `getIndexerLastSuccessVersion` to fetch the last success version from indexer
3. Update waitForTransaction to include this check (Developer can opt-out if preferred)
pnpm fmt
pnpm test
=> Add indexer version sync

src/api/account.ts, src/api/event.ts, src/client/get.ts, src/internal/account.ts, src/internal/event.ts, src/internal/transaction.ts, src/types/index.ts, src/types/indexer.ts, tests/e2e/api/paginate_query.test.ts, tests/e2e/api/transaction_builder.test.ts, tests/e2e/api/transaction_submission.test.ts
Unify indexer and fullnode pagination type into one type and handle the proper assignment in the function.
Note: pagination currently doesnt work for any (fullnode) function that uses `paginateWithCursor` (pretty sure it had never worked) - there is an open item for it, can work on it later.
now 
```
export interface PaginationArgs {
offset?: AnyNumber;
limit?: number;
}
```
before
```
export interface PaginationArgs {
offset?: AnyNumber;
limit?: number;
}
export interface IndexerPaginationArgs {
offset?: number | bigint;
limit?: number;
}
```
pnpm test
=> Unify query pagination types

examples/README.md, examples/javascript/simple_transfer.js, examples/typescript/simple_transfer.ts
* Have single signer examples use `signAndSumitTransaction`
* Update README
=> Fix examples

jest.config.js, tests/e2e/transaction/sign_transaction.test.ts, tests/e2e/transaction/transaction_simulation.test.ts, tests/e2e/transaction/transaction_submission.test.ts
This PR does two things:
1. @0xmaayan observed that sometimes running the full test suite would result in the machine running out of fds. We help avoid this by limiting concurrency in jest. I timed it, on my machine this doesn't seem to affect how long the tests take overall.
2. The user txn processor currently breaks when handling txns with secp256. This is the case across all networks and in main, so it's just totally broken upstream. This PR skips those tests for now to make CI green.
See CI run.
=> [CI] Avoid exhausting file descriptors, disable secp256 tests

examples/javascript/simple_sponsored_transaction.js, examples/typescript/simple_sponsored_transaction.ts, src/api/general.ts, src/bcs/serializable/fixed-bytes.ts, src/internal/coin.ts, src/internal/general.ts, src/transactions/transaction_builder/transaction_builder.ts, src/transactions/types.ts, src/types/index.ts, tests/e2e/api/account.test.ts, tests/e2e/api/general.test.ts, tests/e2e/api/transaction.test.ts, tests/e2e/transaction/generate_transaction.test.ts, tests/e2e/transaction/helper.ts, tests/e2e/transaction/sign_transaction.test.ts, tests/e2e/transaction/transaction_builder.test.ts, tests/e2e/transaction/transaction_simulation.test.ts, tests/e2e/transaction/transaction_submission.test.ts
This makes it so that the the developer doesn't have to define type_arguments when building transactions.  This is the majority use case.  This also changes it to camelCase for consistency for public facing params.  Snake case is still required for serialization.
pnpm test
=> Make type_arguments optional and publically rename to typeArguments

src/types/index.ts
Updated the signature types in our API types to use Secp256k1
Added the actual strings for all signature types:
```typescript
export type TransactionEd25519Signature = {
type: string;
public_key: string;
signature: "ed25519_signature";
};
// etc
````
Also removed some duplicated type code e.g.:
```typescript
export type AccountEd25519Signature = TransactionEd25519Signature;
// instead of redefining the same exact type...
```
#74 will cover testing for these
https://github.com/aptos-labs/aptos-core/tree/main/api/src/tests/transactions_test.rs
=> [Types] Update the signature types in API types to use their actual `type` strings and include Secp256k1

.npmignore, README.md, package.json
* Update README file to include basic usage and references to alpha version
* Update build process to be more informational with browser / cjs / esm / types dist folders
* Have npm to only download src and dist folders and important files like license, readme, etc
* Update package.json
=> Update README and build process

src/api/aptos.ts, src/api/fungible_asset.ts, src/internal/fungible_asset.ts, src/internal/queries/getFungibleAssetMetadata.graphql, src/types/generated/operations.ts, src/types/generated/queries.ts, src/types/indexer.ts, tests/e2e/api/fungible_asset.test.ts
Add the new query getFungibleAssetMetadata. 
Note: This time I am modifying on how we construct the function in `/internal` Please take a look
pnpm fmt
pnpm lint
pnpm test
=> Add new api getFungibleAssetMetadata

src/api/fungible_asset.ts, src/internal/fungible_asset.ts, src/internal/queries/getFungibleAssetActivities.graphql, src/types/generated/operations.ts, src/types/generated/queries.ts, src/types/indexer.ts, tests/e2e/api/fungible_asset.test.ts
Add getFungibleAssetActivities api query
pnpm test
pnpm fmt
=> add api query getFungibleAssetActivities

examples/typescript/move/Move.toml, examples/typescript/move/sources/create_object.move, examples/typescript/move/sources/transfer.move, examples/typescript/multi_agent_transfer.ts, examples/typescript/package.json
This shows swapping coins and an object in one transaction.
Checks balances and all
```
pnpm multi_agent_transfer             
> ts-test@1.0.0 multi_agent_transfer /opt/git/typescript-sdk/examples/typescript
> ts-node multi_agent_transfer.ts
This example will create two accounts (Alice and Bob), fund them, create an object, and transfer the object between them using move scripts and a multi-agent transaction.
=== Addresses ===
Alice's address is: 0x267d0a61dbc8c95f5941c4df71b5b01be2badc33d29b19bf977455b9c45167e5
Bob's address is: 0x804744a3d9ae3382fdc91b81ba1d426ce824da0ca6f6a2f2db5848f15e5ba9e5
=== Funding accounts ===
Alice's fund transaction:  100d8fc56d0bf973df44b0c73acc8b23de3a6b87367dd6524ffa832e3915666b
Bob's fund transaction: …
```
=> [examples] Add a multi-agent script example

src/api/collection.ts, src/internal/collection.ts, tests/e2e/api/collection.test.ts
This adds a function for users to invoke 0x4::aptos_token::create_collection via the SDK
pnpm test
=> Add createCollection API to the SDK

examples/typescript/mint_nft.ts, examples/typescript/package.json, src/api/token.ts, src/internal/queries/TokenActivitiesFieldsFragment.graphql, src/internal/queries/getTokenActivity.graphql, src/internal/queries/getTokenCurrentOwner.graphql, src/internal/token.ts, src/types/generated/operations.ts, src/types/generated/queries.ts, src/types/indexer.ts, tests/e2e/api/token.test.ts
Adds getCurrentTokenOwnerData, getTokenActivities, getOwnedToken queries to the token client.  Adds mintTokenTransaction and a simple example.
pnpm test
=> Finish the token related API for alpha

tests/e2e/transaction/signTransaction.test.ts, tests/e2e/transaction/transactionSimulation.test.ts, tests/e2e/transaction/transactionSubmission.test.ts, tests/unit/account.test.ts
Skip all secp256k1 tests until next devnet release when single signer is supported
=> Skip all secp256k1 tests

CHANGELOG.md, src/api/transactionSubmission.ts, src/internal/transactionSubmission.ts, tests/e2e/transaction/transactionSubmission.test.ts
This adds an API function to publish a move module with the SDK. It is a used function with some of our external partners.
Note: later, when we will have aptos-cli integrated within the SDK, this process would be much more simple!
pnpm test
=> Support publish module API

README.md
We should document this import error due to tsconfig, im putting it in readme for now.
=> add troubleshoot in readme on import error

src/transactions/typeTag/parser.ts, src/transactions/typeTag/typeTagParser.ts, tests/unit/typeTagParser.test.ts
The typetag parser will need to be adjusted for generics and other special cases in an upcoming pull request.
This adds a much simpler parser and has comments for every choice made.
I've put a pretty comprehensive set of tests, including some that are disabled that aren't properly handled in either parser (it can probably be updated in the new one).
Additionally, replaced structTag parsing with this implementation for now.
=> [typeTag] Add new type tag parser for struct tags

CHANGELOG.md, examples/typescript/multi_agent_transfer.ts, examples/typescript/simple_sponsored_transaction.ts, examples/typescript/simple_transfer.ts, src/api/general.ts, src/api/transactionSubmission.ts, src/bcs/serializable/fixedBytes.ts, src/internal/coin.ts, src/internal/digitalAsset.ts, src/internal/general.ts, src/internal/transactionSubmission.ts, src/transactions/transaction_builder/transaction_builder.ts, src/transactions/types.ts, src/types/index.ts, tests/e2e/api/account.test.ts, tests/e2e/api/transaction.test.ts, tests/e2e/client/aptosRequest.test.ts, tests/e2e/transaction/generateTransaction.test.ts, tests/e2e/transaction/helper.ts, tests/e2e/transaction/signTransaction.test.ts, tests/e2e/transaction/transactionBuilder.test.ts, tests/e2e/transaction/transactionSimulation.test.ts, tests/e2e/transaction/transactionSubmission.test.ts
Because `arguments` is a reserved keyword in typescript, when you try to use the spread operator with it in `strict` mode, it doesn't let you.
For example:
```typescript
const transactionBuilder = async(args: {
aptos: Aptos,
sender: Account,
moduleFunction: string,
arguments: Array<EntryFunctionArgumentTypes>,
typeArguments?: TypeTag[],
}): Promise<UserTransactionResponse> => {
const { aptos, sender, moduleFunction, arguments, typeArguments } = args;
// ..
```
The compiler won't let you destructure `args` because `arguments` is reserved. You could of course do `arguments: functionArguments`, but perhaps we should just avoid the reserved keyword entirely to avoid issues
I've also changed each instance of `type_arguments` in the docs to `typeArguments`
I also made sure not to change …
=> [Rename] Change `arguments` in the transaction builder to `functionArguments`, change references in docs

CHANGELOG.md, src/client/get.ts, src/client/post.ts, src/version.ts
- Add clientConfig to header client config override
- Set metric version to 2.0.0 to distinguish between sdk v1 and v2
=> Include client config override and set version for metrics

CHANGELOG.md, src/types/index.ts, tests/e2e/transaction/helper.ts, tests/e2e/transaction/signTransaction.test.ts, tests/e2e/transaction/transactionSimulation.test.ts
This removes needing to do silliness like:
`0x${HexInput.toStringWithoutPrefix()}...`
=> [types] Remove requirement on 0x for input

src/transactions/typeTag/parser.ts, tests/unit/typeTagParser.test.ts
These are required to parse the ABI.  Even though, you can't actually provide them as an input type tag.
Added an appropriate unit test
=> [typeTag] Add signer and &signer to typetag parsing

tests/e2e/transaction/generateTransaction.test.ts, tests/e2e/transaction/transactionBuilder.test.ts
This cleans up tests with some unexpected code.  Both with signing transactions for functions that don't exist, as well as using MoveObject in place of an AccountAddress.
CI
=> Cleanup tests to match expected behavior

CHANGELOG.md, examples/typescript/multi_agent_transfer.ts, examples/typescript/simple_transfer.ts, examples/typescript/transfer_coin.ts, src/api/account.ts, src/internal/account.ts, tests/e2e/api/account.test.ts, tests/e2e/api/faucet.test.ts, tests/e2e/api/general.test.ts
Add ability for direct typed resource calls from the API without having to do conversion.
This should let you read Move resources directly, without having to have your own conversion code.  This also should allow for general type safety, keeping in mind that the underlying resource could possibly not match if it's not correct.
I'm debating how useful this is without something that generates types ahead of time from the ABI, but it also should be pretty easy to generate those.
I added a test that does a direct comparison of the output objects of `getAccountResource` and the typed one, and they are the same, though now there is proper typing to handle it
=> [account] Add ability for custom typed resource calls

src/api/transaction.ts, src/internal/transaction.ts, src/types/index.ts
=> add missing indexerVersionCheck check var to waitForTransaction in api level

examples/typescript/multi_agent_transfer.ts, examples/typescript/simple_transfer.ts, examples/typescript/transfer_coin.ts, src/index.ts, src/internal/coin.ts, src/transactions/typeTag/index.ts, src/transactions/typeTag/parser.ts, src/transactions/typeTag/typeTag.ts, src/types/index.ts, tests/unit/typeTag.test.ts, tests/unit/typeTagParser.test.ts
Use the new TypeTag parser everywhere, with generic support.  This consistency is required for Remote ABI
Existing tests.  Parser is already covered with separate tests, so duplicates were removed.
=> [typeTag] Use new typetag parser everywhere, remove old one

src/api/account.ts, src/api/coin.ts, src/api/event.ts, src/internal/account.ts, src/internal/coin.ts, src/internal/event.ts, src/transactions/types.ts, src/types/index.ts
resolve #117 
Removing the MoveStructType and consolidate into MoveResourceType. 
We could keep both, and assign one to another. i.e 
```
export type MoveStructType = MoveResourceType;
export type MoveResourceType = `${string}::${string}::${string}`;
```
But I feel like it would just confuse the user. 
pnpm fmt
=> consolidate move struct and resource type

CHANGELOG.md, src/core/accountAddress.ts, tests/unit/accountAddress.test.ts
While working on a few things, I realized we don't have a static field for the `0x0` address, and we'll be using it a lot soon
I added simple unit tests for it in `accountAddress.test.ts` and added it to the CHANGELOG
=> [Small change] Add 0x0 to the AccountAddress class as `AccountAddress.ZERO` in anticipation of optional fee payer address

src/transactions/authenticator/transaction.ts, src/transactions/instances/transactionPayload.ts, src/transactions/transaction_builder/transaction_builder.ts, src/types/index.ts
As I'm exporting types for the wallet adapter stuff, I'm coming across inconsistent type names, so I'm trying to make sure they make sense.
```typescript
pnpm jest
```
=> [Naming] Unifying type names so they reflect the rust enums more accurately

CHANGELOG.md, src/core/account.ts, src/core/authenticationKey.ts, src/core/crypto/anyPublicKey.ts, src/core/crypto/ed25519.ts, src/core/crypto/index.ts, src/core/crypto/multiKey.ts, src/core/crypto/secp256k1.ts, src/transactions/authenticator/account.ts, src/transactions/transaction_builder/transaction_builder.ts, src/types/index.ts, tests/e2e/transaction/transactionSubmission.test.ts, tests/unit/account.test.ts, tests/unit/helper.ts, tests/unit/multiKey.test.ts
- Implement `MultiKey` that conforms to [AIP-55](https://github.com/aptos-foundation/AIPs/pull/263).
- Add multiSig example that uses MultiKey class
- Fix verify signature logic on public key module
- Simplify code to use `senderAuthentication` when generating signed transaction as part of the transaction builder flow
- Add clarity and explanations around `Ed25519PublicKey`, `Secp256k1PublicKey` and `AnyPublicKey` classes
Follow up:
- Implement `verifySignature` in `MultiKey` class
pnpm test
=> Implement `MultiKey` authentication key

src/transactions/typeTag/index.ts, tests/unit/typeTagParser.test.ts
1. Adding more explicit return types to facilitate using pattern matching types
2. The `TypeTagVector.toString()` function was returning `vectoru64` instead of `vector<u64>`
3. added `aptosCoinStructTag()` because it's so commonly used
4. changed `stringStructTag()` to be `async function` instead of `const ... async()` to match the others
```typescript
pnpm jest
```
=> [TypeTag] Adding explicit return types for TypeTag types, fix vectors `toString()` function, add aptosCoinStructTag

tests/e2e/transaction/signTransaction.test.ts, tests/e2e/transaction/transactionBuilder.test.ts, tests/e2e/transaction/transactionSimulation.test.ts, tests/e2e/transaction/transactionSubmission.test.ts
Since we loosen the type of MoveStructType, we do not need to specify the `0x` prefix. `toString()` of the address class should include the prefix already.
pnpm test
=> [Easy] Fix MoveStructType address format

src/transactions/transactionBuilder/remoteAbi.ts, tests/e2e/transaction/helper.ts, tests/e2e/transaction/transactionArguments.test.ts, tests/unit/typeTagParser.test.ts
This mixes simple and non-simple args with the already existing tests to ensure that transactions are handled properly.
This also makes the string parsing for addresses less strict
This adds tests specifically to test remote ABI inputs to ensure they work properly.
=> [remoteAbi] Add transaction argument tests for simple args

src/bcs/serializable/moveStructs.ts, tests/unit/bcsHelper.test.ts
Adding factory methods for MoveVector for AccountAddress and MoveOption:
```typescript
MoveVector.AccountAddress
MoveOption.AccountAddress
```
This is from an old PR
added unit tests
`pnpm jest`
=> [Documentation] Fixing typos in documentation

src/core/account.ts, src/core/authenticationKey.ts
Trying to make it clearer (and more explicit) what a derivation/signature scheme is used for and how the authentication keys/account addresses are derived, and what the schemes mean.
=> [Documentation] Update documentation for authentication key/account address derivation

src/api/account.ts, src/api/transactionSubmission.ts, src/internal/transactionSubmission.ts, src/transactions/instances/index.ts, src/transactions/instances/rotationProofChallenge.ts, tests/e2e/api/account.test.ts
This PR creates an new api method rotateAuthKey
Note:
1. I place it under /api folder only and not /internal, because of dependency cycle
2. This only supports legacy ed25519, the move side does not support Single Signer or Secp.
pnpm test
=> Add rotateAuthKey

src/api/transactionSubmission.ts, src/core/crypto/secp256k1.ts, src/internal/transactionSubmission.ts, src/transactions/transactionBuilder/transactionBuilder.ts, src/transactions/types.ts, tests/e2e/transaction/helper.ts, tests/e2e/transaction/transactionBuilder.test.ts, tests/e2e/transaction/transactionSubmission.test.ts
- moving the input arguments into an interface
- flatten interface, removed unneeded `secondarySignerAuthenticators` layer
=> Create input submit transaction interface type

CHANGELOG.md, src/api/transactionSubmission.ts, src/internal/transactionSubmission.ts, src/transactions/transactionBuilder/transactionBuilder.ts, src/transactions/types.ts, tests/e2e/api/coin.test.ts, tests/e2e/transaction/generateTransaction.test.ts, tests/e2e/transaction/transactionBuilder.test.ts, tests/e2e/transaction/transactionSubmission.test.ts
After working with the wallet adapter more, I realized my initial motivation for suggesting @0xmaayan use a `Uint8Array` was misled and premature, because we can perform this conversion at the wallet adapter layer if necessary.
Until it's necessary, it is ideally more strongly typed as an actual RawTransaction instance.
1. This saves us an unnecessary round of serialization/deserialization in `deriveTransaction`
2. Increases clarity, because it's confusing knowing what the `Uint8Array` bytes really are
3. We can very easily just perform this conversion at the wallet adapter layer when it's necessary
After trying to build transactions/come up with a more intuitive flow, I realized how premature converting to bcs bytes was, and that's the motivation for this PR.
```typescript
pnpm jest
```
=> Replace all instances of `rawTransaction: Uint8Array` with an actual `RawTransaction`

package.json, pnpm-lock.yaml, src/internal/ans.ts, tsconfig.json, tsup.config.js, tsup.config.ts
The `esm` bundle was not working properly and would only import the `dist/types`, not any of the functions, classes, variables, etc that were expected. This was because the `types` and `esm` were not colocated in the same output directory.
You can build with the script
```bash
pnpm build:tsup
```
Also `.env` vars were not included in `tsup` and were causing browser-based projects that consumed `@aptos-labs/ts-sdk` to crash due to `ReferenceError: process is not defined`
[Guide on tsup](https://dev.to/orabazu/how-to-bundle-a-tree-shakable-typescript-library-with-tsup-and-publish-with-npm-3c46)
[Example package.json](https://github.com/chakra-ui/panda/blob/main/packages/core/package.json)
[Slack thread](https://aptos-org.slack.com/archives/C05NLAKJM9U/p1699071799795639?thread_ts=1699046504.3 …
=> [tsup] Correctly bundle esm and cjs with tree-shaking

CHANGELOG.md, src/internal/event.ts, src/internal/queries/getEvents.graphql, src/types/generated/operations.ts, src/types/generated/queries.ts, src/types/generated/types.ts
Add new `indexed_type` field for `events` query
https://aptos-org.slack.com/archives/C03MN5F7WUV/p1697815925868219
`getAccountEventsByEventType` test is failing because localnet needs to be regenerate with the new field, @banool is working on it
https://aptos-org.slack.com/archives/C03MN5F7WUV/p1699286279415299?thread_ts=1697815925.868219&cid=C03MN5F7WUV
=> Add and use `indexed_type` field

CHANGELOG.md, src/api/transactionSubmission.ts, src/internal/transactionSubmission.ts, src/transactions/types.ts, tests/e2e/transaction/generateTransaction.test.ts, tests/e2e/transaction/helper.ts, tests/e2e/transaction/transactionSimulation.test.ts, tests/e2e/transaction/transactionSubmission.test.ts
1. Added "hasSponsor" field to all `InputGenerateTransactionData`. If set to `true`, feepayer address will be overrided to "0x0".
2. Fee payer will have to use "signTransactionAsPayer" to sign the transaction.
```
Test Suites: 38 passed, 38 total
Tests:       1 skipped, 450 passed, 451 total
Snapshots:   0 total
Time:        24.384 s, estimated 25 s
```
=> Optional Fee Payer

src/client/core.ts, src/transactions/transactionBuilder/remoteAbi.ts, src/transactions/transactionBuilder/transactionBuilder.ts, src/types/index.ts, tests/e2e/client/aptosRequest.test.ts
Some fixes to the SDK while working on the wallet adapter
1. Type `params` in remote abi fetch flow with `TypeTag[]`
2. Remove unneeded function overload
3. Rename TOKEN => AUTH_TOKEN 
4. Use AUTH_TOKEN only for faucet requests - need to find a nicer way here
5. Add API_KEY for future use
=> Some fixes across the SDK

.github/actions/run-examples/action.yaml
The other action has this. Without it, you can't see why the local testnet failed to start / crashed.
=> Print logs from local testnet on failure for examples CI

CHANGELOG.md, examples/typescript/swap.ts, src/api/general.ts, src/internal/general.ts, src/types/index.ts, tests/e2e/api/general.test.ts
Renaming `ViewRequestData` to `InputViewRequestData` to adhere to our naming conventions
I mostly did this because I came across `ViewRequest` which seems to be the JSON payload response type from the node. Am I correct in my understanding @0xmaayan ?
`pnpm jest`
Updated `CHANGELOG.md` as well to note that it's a breaking change
=> [Rename] Changing ViewRequestData => InputViewRequestData

CHANGELOG.md, src/transactions/transactionBuilder/transactionBuilder.ts, tests/e2e/transaction/transactionBuilder.test.ts
Although we give the option to pass in `maxGasAmount` value when generating transaction, we dont respect it.
=> Respect max gas amount value

.eslintignore, .github/actions/run-examples/action.yaml, examples/typescript-esm/.npmrc, examples/typescript-esm/pnpm-lock.yaml
- Typescript-esm examples had to be added manually, and now are there
- Ignoring build artifacts that if left around from examples would cause lint to fail
Built locally, tested the build artifacts accordingly.
Examples will be tested in the CI for this PR.
=> [examples] Add typescript-esm to CI, ignore build artifacts in lint

src/api/account.ts, src/api/coin.ts, src/api/event.ts, src/internal/account.ts, src/internal/coin.ts, src/internal/event.ts, src/transactions/transactionBuilder/helpers.ts, src/transactions/types.ts, src/types/index.ts
Struct types were not able to be used as MoveValue which breaks some use cases.  Additionally, the MoveStructType has been renamed to MoveStructId as there was some strange merging of the two.
CI, but need to follow up with a full suite of tests on view function outputs.
=> [MoveValue] Cleanup types to match the proper types

src/api/general.ts, src/internal/general.ts, tests/e2e/api/general.test.ts
Similar to getResource, but typed accordingly with MoveValue[] as the default. Only types that extend that can be used.
This adds a few view function input and output type tests.  Full tests will need a module properly published for it to work.
=> [view] Add generic for typing view function outputs

CHANGELOG.md, src/transactions/typeTag/parser.ts, tests/unit/typeTagParser.test.ts
While using the `typeTagParser(...)` function, I was getting this error:
```shell
TypeTagParserError: Failed to parse typeTag 'T0', unknown type.
```
I added a clearer error message if the string matches a generic type but generics are disallowed:
```shell
TypeTagParserError: Failed to parse typeTag 'T0', unexpected generic type.
```
Updated the tests
```shell
pnpm jest typeTagParser.test.ts
```
=> [Error message] Adding a clearer error message for when the typeTagParser encounters a generic but generics aren't allowed

src/api/ans.ts, src/internal/ans.ts, tests/e2e/ans/ans.test.ts
This adds the remaining P0 contract APIs for ANS. There are a few indexer queries to pull in after this PR gets merged. The functions include:
* Registering a subdomain via `registerName`
* Setting and Getting primary name for an account `getPrimaryName` and `setPrimaryName`
* Setting and Getting target addresses for a name `getTargetAddress` and `setTargetAddress`
* Renewing a domain with `renewDomain`. **Note**, this is `Domain` and not `Name` as subdomains are not renewable.
**Note**: I am currently skipping one test for name renewal. I need to work with someone on the contract side to see what is going on. I think I might be missing one config variable when setting up the contract.
E2E test suite
_na_
=> Adds additional ANS contract APIs

CHANGELOG.md, src/client/core.ts, tests/e2e/client/aptosRequest.test.ts
We recently add API_KEY to clientConfig but never really respect it. With this change, one can
```
const aptosConfig = new AptosConfig({
network: Network.TESTNET,
clientConfig: {
API_KEY: "my-key",
},
});
```
=> Respect api key header config

CHANGELOG.md, src/api/ans.ts, src/internal/ans.ts, tests/e2e/ans/ans.test.ts
ANS had 3 different implementations for times. This converts all uses of time to be milliseconds since the epoch. 
Updated and passing test cases
https://aptos-org.slack.com/archives/C05NLAKJM9U/p1700245777573069
=> Unifies ANS dates

src/api/account.ts
Comment is misleading, the SDK unwraps `data` and returns what is inside it.
Tested manually, the output of the function is not keyed by `data`.
=> Fix comment on getAccountResource

README.md
Adds badges for showing info about the experimental version.  I suspect we'll likely want to continue using an experimental version for breaking changes.
=> [README] Add badges for latest version vs experimental

src/transactions/transactionBuilder/transactionBuilder.ts, tests/e2e/transaction/transactionBuilder.test.ts
This pull request addresses an issue in the `generateRawTransaction` function where the `getInfo` function throws an error when the account is not on the chain, and manually setting the account sequence number to 0 was ineffective due to the falsy nature of this value. The proposed solution involves a minor adjustment to ensure more robust handling of the account sequence number. This modification replaces the falsy check with a comparison to `undefined`, providing a more accurate and reliable method for handling the account sequence number.
A new test case has been added to verify the behavior when generating a raw transaction with an account not on the chain and the account sequence number set to 0. Additionally, an error scenario has been tested where an attempt is made to generate a …
=> fix zero account sequence number

CHANGELOG.md, examples/typescript/move/facoin/sources/fa_coin.move, examples/typescript/publish_package_from_filepath.ts, examples/typescript/your_fungible_asset.ts, src/api/fungibleAsset.ts, src/internal/fungibleAsset.ts
- Add `your_fungible_asset` example (https://github.com/aptos-labs/aptos-core/blob/main/ecosystem/typescript/sdk/examples/typescript/your_fungible_asset.ts)
- Add `transferFungibleAsset` function to generate a transaction to transfer a fungible asset from sender's primary store to recipient's primary store
same output from existing example https://aptos.dev/tutorials/your-first-fungible-asset/#step-32-completing-the-example
```
Transaction hash: 0xc61eb3c2a9d1ac1761fc679a6a70ce595933cc7c2cc1a4ab7335c9ee3e2386cf
All the balances in this exmaple refer to balance in primary fungible stores of each account.
Alice's initial FACoin balance: 0.
Bob's initial FACoin balance: 0.
Charlie's initial balance: 0.
Alice mints Charlie 100 coins.
Charlie's updated FACoin primary fungible store balance: …
```
=> Add `your_fungible_asset` example and `transferFungibleAsset` function

CHANGELOG.md, examples/typescript/multi_agent_transfer.ts, examples/typescript/your_fungible_asset.ts, src/bcs/deserializer.ts, src/bcs/serializer.ts, src/core/accountAddress.ts, src/internal/ans.ts, src/internal/event.ts, src/internal/faucet.ts, src/internal/staking.ts, src/internal/transactionSubmission.ts, src/transactions/instances/moduleId.ts, src/transactions/transactionBuilder/remoteAbi.ts, src/transactions/transactionBuilder/transactionBuilder.ts, src/transactions/typeTag/parser.ts, tests/e2e/ans/publishANSContracts.ts, tests/e2e/api/account.test.ts, tests/e2e/transaction/transactionArguments.test.ts, tests/unit/accountAddress.test.ts, tests/unit/deserializer.test.ts, tests/unit/serializer.test.ts
More often than not the SDK receives addresses that are shortened.  This is very possible to occur, and it should be allowed as an input as default.  Strictness should only be applied if wanted, and until there is a different address standard, it should accept any output from the API.  Otherwise, strings won't be easily converted.
We can disable this once we add full type bindings to do on the fly struct conversion rather than use JSON intermediaries.
I simply flipped relaxed to normal, and added a strict.  The CI should run enough tests to cover it.
=> [accountAddress] Make strict mode optional, and relaxed default

src/transactions/transactionBuilder/remoteAbi.ts, src/transactions/typeTag/index.ts, tests/unit/remoteAbi.test.ts
This provides nearly full coverage of all the parsing logic, as well as fixed a couple bugs in the parsing logic.
This tests all inputs and outputs, along with mixed inputs, and ensures that they pass correctly.
I purposely did not spend time to check all the error messages explicitly to save time, but coverage shows they are covered.
=> [remoteAbi] Add argument parsing unit tests

src/transactions/transactionBuilder/remoteAbi.ts, src/transactions/types.ts, tests/unit/remoteAbi.test.ts
To support old SDK compatibility, we've done following breaking changes:
* Remove Hex string as an input for simple args, this needs to be converted prior
* String as an input will be directly converted to UTF-8 bytes
* ArrayBuffer is also a valid input, and will be parsed similarly to Uint8array
We could in the future plan to support other inputs like 
* Uint16array
* Uint32array
* BigUint64array
Added more unit tests appropriately
Resolves https://github.com/aptos-labs/aptos-ts-sdk/issues/202
=> [remoteAbi] Cleaned up behavior for strings as Vector<u8>

CHANGELOG.md, src/internal/digitalAsset.ts, tests/e2e/api/digitalAsset.test.ts
Following https://github.com/aptos-labs/aptos-ts-sdk/pull/238, we can now support an array value in digital asset property map
To pass in an array value, use a string type - i.e `"[hello, 1, true, world]"`
pnpm run test
=> Add support to Array in digital asset property map

CHANGELOG.md, src/transactions/types.ts
`maxGasAmount, gasUnitPrice, expireTimestamp` properties should be represented as `number` type.
First,`bigint` causes serialization issues for dapps and wallets and second these property values fall within the JS number type range. 
https://aptos-org.slack.com/archives/C06BFEMLAKT/p1703193020312399
Next - once this PR lands, wallet adapter should be updated to use the new sdk version and types.
=> Update transaction option `maxGasAmount, gasUnitPrice, expireTimestamp` properties to use `number` type

CHANGELOG.md, src/bcs/consts.ts, tests/unit/deserializer.test.ts, tests/unit/serializer.test.ts
Doing powers of bigints doesn't work on older versions of node, and it seems to be hard to reproduce, but still occurs.  Hardcoding these should have the same behavior, without these quirks.
Fixes https://github.com/aptos-labs/aptos-wallet-adapter/issues/223
TBD, making a test now with an older version of node to check
Related https://github.com/aptos-labs/aptos-core/pull/11540
=> [consts] Make upper bound numbers hardcoded

CHANGELOG.md, src/api/aptos.ts
Fix https://github.com/aptos-labs/aptos-ts-sdk/issues/243 
`build | simulate | submit` properties are available on `aptos` namespace but they are not functional - that causes confusion for devs that could see those properties on autocomplete under the `aptos` namespace but then their program breaks. Those properties should only be visible under the `aptos.transaction` namespace
pnpm test
and 
```
const aptos = new Aptos();
aptos. // autocomplete should not show build | simulate | submit
aptos.transaction // autocomplete should show build | simulate | submit
```
=> Omit `build | simulate | submit` from aptos namespace

examples/typescript/transfer_coin.ts, src/api/coin.ts, src/internal/coin.ts, tests/e2e/api/coin.test.ts, tests/e2e/client/customClient.test.ts
Follow up on [slack thread](https://aptos-org.slack.com/archives/C05NLAKJM9U/p1704496831185589) sender does not need to be an `Account` type, it can just be an `AccountAddressInput`. It's helpful to change it to an address in the event you don't have access to the user's private key.
```bash
pnpm lint && pnpm unit-test && pnpm fmt && pnpm build
```
=> [coin] transferCoinTransaction sender type change to AccountAddressInput

CHANGELOG.md, src/client/core.ts, tests/e2e/client/aptosRequest.test.ts
For custom URLs, users might define a url with a forward slash (`/`). The SDK appends a forward slash be default and it can lead to errors.
```
https://www.domain.com/v1/ -> SDK will change it to https://www.domain.com/v1//
```
This PR remove the default forward slash append so URLs stay the same
=> Remove request url forward slash append

CHANGELOG.md, examples/typescript/batch_funds.ts, examples/typescript/batch_mint.ts, package.json, pnpm-lock.yaml, src/api/aptos.ts, src/api/transaction.ts, src/api/transactionSubmission/management.ts, src/transactions/management/transactionWorker.ts
The transaction management is a send-and-forget process in a way that once transactions are sent to worker, the dapp is not aware of what is going on unless a potential error happens.
This PR adds logic for the `TransactionWorker` module to fire events during a worker task and dapp can listen to these events.
```
aptos.transaction.batch.on(TransactionWorkerEvents.ExecutionFinish, async (data) => {
console.log("execution finish", data);
});
```
Note:
Currently, dapp uses `aptos.batchTransactionsForSingleAccount()` to start the worker. We now introduce a dedicated namespace under `aptos.transaction.batch` where one can use `aptos.transaction.batch.forSingleAccount()` same as before. This is for potential future enhancement of the worker and to conform with the sdk design.
`pnpm test` …
=> `TransactionWorker` to fire events a dapp can listen to

CHANGELOG.md, package.json, pnpm-lock.yaml
Without this, it will fail to run with
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'eventemitter3' imported from /opt/git/aptos-playground/node_modules/.pnpm/@aptos-labs+ts-sdk@1.5.0/node_modules/@aptos-labs/ts-sdk/dist/esm/chunk-27YNIEGN.mjs
=> [deps] Move event emitter to runtime dependency

src/transactions/transactionBuilder/transactionBuilder.ts
Transaction simulations would fail whenever used with the zkid public key. It defaults to AccountAuthenticatorEd25519 when it should be defaulting to AccountAuthenticatorSingleKey
Tested in the example, `zkid.ts`
```
const alice = await aptos.deriveAccountFromJWTAndEphemAccount({
jwt: jwtToken,
ephemeralAccount: aliceEphem,
pepper,
});
const txn = await aptos.transaction.build.simple({
sender: alice.accountAddress,
data: {
function: "0x1::coin::transfer",
typeArguments: [APTOS_COIN],
functionArguments: [bob.accountAddress, TRANSFER_AMOUNT],
},
});
aptos.transaction.simulate.simple({
signerPublicKey: alice.publicKey,
transaction: txn
})
```
=> [feat] Add simulation for zkid public key

CHANGELOG.md, src/api/aptosConfig.ts, src/client/core.ts
When having API errors it is hard to understand what server errors out and most likely we get something like
```
AptosApiError: database query error
```
That is not really helpful in understanding WHAT service is down between the 3 - indexer, fullnode, faucet
=> Add more meaningful API error messages

CHANGELOG.md, src/transactions/transactionBuilder/transactionBuilder.ts, tests/e2e/transaction/transactionBuilder.test.ts, tests/e2e/transaction/transactionSubmission.test.ts
[AIP-52](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-52.md) introduced automated account creation for sponsored transactions. This PR supports this change by if the transaction is a sponsored transaction, check the main signer chain info. If it is not found, assign the sequence number to 0.
`pnpm test`
=> Support automated account creation for sponsored transactions

CHANGELOG.md, src/internal/ans.ts, src/utils/apiEndpoints.ts, tests/unit/aptosConfig.test.ts
=> Add randomnet to known networks

CHANGELOG.md, examples/typescript-esm/package.json, examples/typescript-esm/transaction_with_predefined_abi.ts, src/api/digitalAsset.ts, src/internal/coin.ts, src/internal/digitalAsset.ts, src/internal/fungibleAsset.ts, src/internal/transactionSubmission.ts, src/transactions/management/transactionWorker.ts, src/transactions/transactionBuilder/transactionBuilder.ts, src/transactions/typeTag/index.ts, src/transactions/typeTag/parser.ts, src/transactions/types.ts, tests/e2e/transaction/generateTransaction.test.ts, tests/e2e/transaction/transactionBuilder.test.ts, tests/e2e/transactionManagement/transactionWorker.test.ts
In testing, removing remote ABI and fetching the sequence number
and gas can reduce submission latency by roughly 50%
E2E example to test
Using Devnet:
From Aptos labs:
```
=== Remote ABI, normal inputs ===
Time for building: 127ms | submission: 178ms | total E2E: 452ms
=== Remote ABI, BCS inputs ===
Time for building: 75ms | submission: 117ms | total E2E: 396ms
=== Local ABI, normal inputs ===
Time for building: 69ms | submission: 113ms | total E2E: 387ms
=== Local ABI, BCS inputs ===
Time for building: 67ms | submission: 108ms | total E2E: 381ms
=== Local ABI, BCS inputs, sequence number already cached ===
Time for building: 41ms | submission: 84ms | total E2E: 361ms
=== Local ABI, BCS inputs, sequence number and gas already cached ===
Time for building: 35ms | submission: 74ms | total …
```
=> [transaction] Allow local ABI instead of remote ABI

docs/@aptos-labs/.nojekyll, docs/@aptos-labs/index.html, docs/@aptos-labs/index.md, docs/@aptos-labs/ts-sdk-latest/.nojekyll, docs/@aptos-labs/ts-sdk-latest/index.html, docs/@aptos-labs/ts-sdk-latest/index.md, scripts/generateDocs.sh
Finally tested locally on my local repo
https://gregnazario.github.io/aptos-ts-sdk/
https://gregnazario.github.io/aptos-ts-sdk/@aptos-labs/ts-sdk-latest
That will allow us to have a "latest" link properly, and we'll probably later have to deal with something fancier to select which version of the docs is wanted.
=> [docs] Add redirects for latest page

CHANGELOG.md, src/api/event.ts, src/internal/event.ts, tests/e2e/api/event.test.ts
Add new event API to get module event from indexer.
Uint test.
https://github.com/aptos-labs/aptos-developers/discussions/6
=> Add API to get module event 

.gitignore, docs/@aptos-labs/ts-sdk-latest/index.md.bak, docs/index.md, scripts/generateDocs.sh
I missed a couple details in the update script for the version, and this should now be fixed (and fix the mess ups from the last one)
=> [docs] Fix release script to properly handle docs updates

src/api/aptosConfig.ts, src/utils/const.ts
For some reason, TSC does not like this Network.DEVNET constant, even though the message specifically says, enum literals are okay.
This allows `tsc -b` to work properly on its own, and I've tested with the examples and other locations.
This has no actual behavior change (probably should be released with a patch version).  The DEFAULT_NETWORK constant is probably not very useful, given that most users would change it to the network they expect.
I discovered this trying to build a CLI with a prebuilt example, but tsc -b would always fail with:
```
node_modules/.pnpm/@aptos-labs+ts-sdk@1.8.0/node_modules/@aptos-labs/ts-sdk/dist/esm/utils/const.d.mts:9:33 - error TS2304: Cannot find name 'Network'.
9 declare const DEFAULT_NETWORK = Network.DEVNET;
~~~~~~~ …
```
=> [bugfix] Fix TSC when compiling using SDK

CHANGELOG.md, src/internal/queries/currentTokenOwnershipFieldsFragment.graphql
Was added as part of https://github.com/aptos-labs/aptos-ts-sdk/pull/291/files#diff-229f58a820e940aade5b67f09fa23edbb936998678b506411112c2b6add2fefe and broke some queries
https://aptos-org.slack.com/archives/C05NLAKJM9U/p1709164127936519
=> Remove decimals field from CurrentTokenOwnershipFields fragement

CHANGELOG.md, README.md, tsup.config.ts
Following discussions, we decided to remove IIFE build support
1. It increases the overall package size in more than 2MB
2. Creates issues when integrating packages without IIFE support
3. If we do want to support those packages we need to inject polyfills which highly increased maintenance work and package size
4. We dont feel there is a valid reason for devs to use IIFE format these days
https://aptos-org.slack.com/archives/C03N83P7QUC/p1709228938688099
https://aptos-org.slack.com/archives/C066E8D05P0/p1709162304228609
=> Deprecate IIFE build support

src/api/general.ts, src/api/transaction.ts, src/types/index.ts, src/utils/apiEndpoints.ts
This is part of the migration to API Gateway. More context here: https://www.notion.so/aptoslabs/Migration-1-Legacy-URL-to-API-Gateway-migration-b007742490684b9bab3debd674504a94.
I found the initial files to change like this:
```
rg -l -e 'fullnode\.[a-z]{3,6}net.aptoslabs.com'
```
I then did a find replace from `fullnode.([a-z]{3,6}net).aptoslabs.com` to `api.$1.aptoslabs.com`.
I did some further digging, e.g. for places where we perhaps build the URL, by just looking at every file that references `aptoslabs.com`. Hopefully this is everything.
I haven't touched indexer API, we'll do that in another PR.
CI for now.
=> Use node API via API Gateway

.github/actions/run-check-version/action.yaml, .github/workflows/run-check-version.yaml, CHANGELOG.md, examples/typescript/asset_uploader.ts, examples/typescript/package.json, examples/typescript/pnpm-lock.yaml, package.json, pnpm-lock.yaml, src/api/aptosConfig.ts, src/index.ts, src/plugins/assetUploader/index.ts, src/plugins/assetUploader/irys.ts, src/plugins/assetUploader/type.ts, src/plugins/assetUploader/types.ts, src/plugins/index.ts, tests/e2e/api/digitalAsset.test.ts
This PR introduces a generic `AssetUploader` module and [Irys](https://docs.irys.xyz/developer-docs/irys-sdk) asset uploader provider as an optional dependency. 
We integrate `irys` package as a peer (optional) dependency to not add too much noise and maintenance for SDK users by forcing them to have a core dependency for a functionality they might not need. 
For users who want to use the SDK asset uploader, and more specifically Irys, they should install the `@irys/sdk` package manually.
The SDK knows how to resolve whether the host package has the Irys package or not. If it doesnt and it tries to use Irys, the SDK would let the user know they should install the Irys package.
If the host package has Irys dependency with a lower version than what the SDK expects, it would warn the user …
=> Introduce `AssetUploader` module and integrate `Irys` as an asset uploader provider

.github/actions/run-check-version/action.yaml, .github/workflows/run-check-version.yaml
Used it on this PR https://github.com/aptos-labs/aptos-ts-sdk/pull/318/commits/ab6357729db287e22b6634428229d143788cf8c8
=> Run check-version CI only on PRs with `main` as the branch target

CHANGELOG.md, src/internal/digitalAsset.ts
Filter `amount > 0` when fetching current digital asset ownership since Indexer marks token `amount` as `0` if it’s been transferred out or burnt.
=> Filter `getCurrentDigitalAssetOwnership` where amount > 0

CHANGELOG.md, src/api/general.ts, src/types/codegen.yaml, src/utils/apiEndpoints.ts, src/utils/const.ts
This is part of the migration to API Gateway. More context here: https://www.notion.so/aptoslabs/Migration-1-Legacy-URL-to-API-Gateway-migration-b007742490684b9bab3debd674504a94.
I found the initial files to change like this:
```
rg -l 'aptoslabs.com'
```
CI for now.
=> Use indexer API via API Gateway

package.json, src/core/crypto/keyless.ts
The order of fields in the `serialize` and `deserialize` methods was different for the `KeylessSignature` class, resulting in a deserialization error.
This PR makes sure the order of fields is matching. (following order of class members)
=> Fixed `KeylessSignature` serialization

tests/e2e/api/digitalAsset.test.ts
When testing locally with a release mode local testnet these tests would sometimes time out. The job of these tests is not to catch regressions in timing or anything, it is to test correctness. Let's give them more time.
CI
N/A
=> Increase digital asset e2e test suite timeout

CHANGELOG.md, src/api/aptosConfig.ts, src/client/core.ts, src/client/get.ts, src/client/post.ts, src/types/index.ts, tests/e2e/client/aptosRequest.test.ts, tests/e2e/client/get.test.ts, tests/e2e/client/post.test.ts, tests/unit/aptosConfig.test.ts
This PR adds the ability to set client configuration per back-end server (resolves https://github.com/aptos-labs/aptos-ts-sdk/issues/258 )
- Allow setting per-backend client config
- `AUTH_TOKEN` moved to be under `faucetConfig` as it is faucet config only
- Handle `Unauthorized` server error
- Clean up and simplify code
- tests are passing
- added new test files
=> Add support to allow setting per-backend configuration

CHANGELOG.md, src/core/account/index.ts, src/core/account/utils/address.ts, src/core/account/utils/index.ts, tests/unit/address.test.ts
Following https://aptos-org.slack.com/archives/C05NLAKJM9U/p1711053989343899 , adding local object address calculation
=> calculate object address and token address

examples/typescript/custom_client.ts, src/api/aptosConfig.ts, src/client/core.ts, src/client/get.ts, src/client/post.ts, src/utils/const.ts, tests/e2e/client/aptosRequest.test.ts
If your custom client is setup improperly, it'll throw "faucet error" on indexer errors.  This cleans it up, and fixes the examples to work properly with indexer.
Tested with the indexer query locally, it failed previously.
=> Fix confusing errors in custom clients

CHANGELOG.md, src/internal/ans.ts
**Update:**
This will be a two step refactor. This PR just fixes the imidiate issues. A future PR will address the points listed bellow. 
**Original context**
This PR addresses ANS queries that return values for expired or inactive names when they should not. 
Questions to answer: 
- The following functions directly hit the `router` and not the indexer. As a result, they will return values even if the name is expired. Do we want to shift these to using the indexer and return `null` for expired names? 
- `getOwnerAddress` 
- `getExpiration` 
- `getTargetAddress`
- `getPrimaryName` (Need to investigate this one.)
- The following APIs use the indexer and ensure that expiration date is valid, should be fine, but good to double check.
- `getAccountNames`
- `getAccountDomains`
- …
=> Updates queries for ANS to ignore expired names

README.md
When someone is using the TypeScript SDK, they will need the reference docs. As of now, the only way to find them is to notice the link in the top-right corner in the "About" section, which is quite hard to find. 
The reference docs show everything in the README anyway, so we want users to click that link right away. They'll get all the same information and more.
Inspection. It looked understandable in preview mode.
N/A
=> Make reference docs very prominent in the README

CHANGELOG.md, src/core/crypto/ed25519.ts, src/core/crypto/secp256k1.ts, src/core/crypto/utils.ts, src/core/hex.ts, tests/unit/account.test.ts, tests/unit/ed25519.test.ts, tests/unit/helper.ts, tests/unit/hex.test.ts, tests/unit/multiEd25519.test.ts, tests/unit/secp256k1.test.ts
resolves https://github.com/aptos-labs/aptos-ts-sdk/issues/309
To verify or sign a message, we should pass the message as a Hex string or Uint8Array type. We can't enforce Hex string type on TS level (since how do you know if it a Hex string or a string? i.e `123abc`). Therefore we check if the message is of type `string`, if it does we check if it is a valid `Hex string` and if it is not we convert it into a `Buffer` type.
In addition, change `Hex.fromString` to `Hex.fromHexString` for clarity
added tests
=> Verify correct message format when sign a message and/or verify signature

CHANGELOG.md, examples/typescript-esm/multisig_v2.ts, examples/typescript-esm/sponsored_transactions/server_as_sponsor.ts, examples/typescript-esm/sponsored_transactions/server_signs_and_submit.ts, examples/typescript/external_signing.ts, src/api/ans.ts, src/api/coin.ts, src/api/digitalAsset.ts, src/api/fungibleAsset.ts, src/api/transaction.ts, src/api/transactionSubmission/build.ts, src/internal/ans.ts, src/internal/coin.ts, src/internal/digitalAsset.ts, src/internal/fungibleAsset.ts, src/internal/transactionSubmission.ts, src/transactions/instances/index.ts, src/transactions/instances/multiAgentTransaction.ts, src/transactions/instances/simpleTransaction.ts, src/transactions/management/transactionWorker.ts, src/transactions/transactionBuilder/transactionBuilder.ts, src/transactions/types.ts
solves https://github.com/aptos-labs/aptos-ts-sdk/issues/259 
Following requests to simplify the communication between servers when sending transactions, this PR introduces new modules for generated transactions - `SimpleTransaction` and `MultiAgentTransaction`.
With these changes, a server can easily serialize a transaction and send to another server for easy deserialization.
**Before:**
The generated `transaction` is of a simple type and can't be bcs serialized. Therefore we need to serialize the `rawTransaction` and send it to the server along with other needed transaction details.
```
const rawTransactionBytes = transaction.rawTransaction.bcsToBytes();
const feePayerAddressByes = sponsor.accountAddress.bcsToBytes();
const serializedSenderAuthenticatorBytes = senderAuth.bcsToBytes(); …
```
=> Introduce Serializable transaction modules

tests/e2e/client/post.test.ts
Previously this would pass:
```
npx jest tests/e2e/client/post.test.ts
```
This would not:
```
pnpm run e2e-test -t 'faucet it sets correct headers'
```
This is because the faucet test was relying on changes made by the first two tests.
This PR fixes that by using separate clients for each test and fixing the invalid assertions.
I also make the tests run against localnet so there is no need for this try / catch (which was only there bc of some API key rejection stuff that doesn't happen locally) and update all the assertions accordingly.
See description.
https://aptos-org.slack.com/archives/C05NLAKJM9U/p1712252143249939
=> Fix shared state problem with post.test.ts, use localnet

src/cli/localNode.ts, tests/e2e/api/general.test.ts, tests/e2e/client/aptosRequest.test.ts
A few changes in one PR. I'll rebase rather than squash:
- **Increase wait time for local testnet startup**
- **Hit / in api_token for full node requests test, log on error**
- Log to help debug why it failed.
- **Use decimals function rather than is_registered in function generics test**
See that CI passes, hopefully with fewer retries than normally required.
=> Fix flakiness in E2E tests

CHANGELOG.md, examples/typescript/external_signing.ts, examples/typescript/package.json, examples/typescript/pnpm-lock.yaml, package.json, pnpm-lock.yaml, src/core/crypto/ed25519.ts
We already use `@noble/curves/secp256k1` for other signing, this brings it in alignment so we only use one signing library `@noble/curves`.
It generally reads better and is more recently updated.
CI
=> [deps] Switch crypto library to @noble/curves

CHANGELOG.md, src/client/core.ts, src/types/index.ts, tests/e2e/client/aptosRequest.test.ts
Include the method used in the sdk when making a server call in the request header to analyze user usage
=> Include `aptos-typescript-sdk-origin-method` header on server request

CHANGELOG.md, examples/typescript/localNode.ts, package.json, tsup.config.ts
`LocalNode` module can only be used in a Node environment and therefore it is not exported by default from the SDK (to not break web environment).
This change exports the CLI folder under the module relative path - that way it is not exported by default and if anyone wants to use it, they can explicitly require it in their node app.
Note: The `LocalNode` requires `tree-kill` package dependency
=> Export LocalNode module under the module relative path

CHANGELOG.md, src/core/crypto/ed25519.ts, src/core/crypto/secp256k1.ts, tests/unit/ed25519.test.ts
Adds malleability verification to SDK, copied from Rust code
See unit tests
=> [crypto] Add malleability check on EDD2519 verification

CHANGELOG.md, src/internal/transaction.ts, tests/e2e/api/transaction.test.ts
In aptos-core we now have exposed the API to do a long poll while waiting for a txn (commit https://github.com/aptos-labs/aptos-core/commit/29a9f0c3f38bb3ddab0517b0fa7aa20804b57f37). This waits for about 1s for the txn to complete.
In this change, the 'waitForTransaction' API in the SDK tries to call the long wait with the goal of exposing the subsecond E2E latencies to the end users. In the long wait is not sufficient then we fall back to polling based wait we already have
=> Change the 'waitForTransaction' SDK API to try long poll

CHANGELOG.md, examples/typescript-esm/transaction_with_predefined_abi.ts, src/internal/transactionSubmission.ts, src/transactions/transactionBuilder/transactionBuilder.ts, src/utils/apiEndpoints.ts
This provides general performance upgrades to the SDK on submission of transactions.
Performance before upgrades (caching turned off)
```
=== Remote ABI, normal inputs ===
Time for building: 245.67583300000024ms | signing 3.397457999999915ms submission: 74.88608400000021ms | total E2E: 617.3080000000004ms
=== Remote ABI, BCS inputs ===
Time for building: 252.75995799999964ms | signing 3.7125000000005457ms submission: 76.13624999999956ms | total E2E: 711.8725830000003ms
=== Local ABI, normal inputs ===
Time for building: 281.67945899999995ms | signing 3.238916000000245ms submission: 80.9857920000004ms | total E2E: 738.3943750000008ms
=== Local ABI, BCS inputs ===
Time for building: 233.43504099999973ms | signing 2.6963340000002063ms submission: 71.50787500000024ms | total E2E: …
```
=> [abi] Fix local ABI to use local version

CHANGELOG.md, src/transactions/transactionBuilder/transactionBuilder.ts, src/utils/index.ts, src/utils/normalizeBundle.ts
When using a wallet extension, objects returned from the wallet belong to the wallet's bundle.
If we pass those objects directly to the ts-sdk, the `instanceof` operator doesn't work.
The change implemented in this PR is a temporary fix, to make sure that the submission flow from a walle extension works as expected.
Ideally, we should try to avoid `instanceof` as much as possible, unless we can guarantee the object was instantiated from the same bundle.
CI
https://github.com/aptos-labs/aptos-ts-sdk/assets/7707719/51e8b0a8-5f69-44f2-9e20-249cec4f2ce4
=> Fix transaction submission from different bundle

.github/actions/run-examples/action.yaml, examples/typescript/batch_funds.ts, examples/typescript/batch_mint.ts, examples/typescript/custom_client.ts, examples/typescript/external_signing.ts, examples/typescript/multi_agent_transfer.ts, examples/typescript/package.json, examples/typescript/publish_package_from_filepath.ts, examples/typescript/rotate_key.ts, examples/typescript/sign_struct.ts, examples/typescript/simple_sponsored_transaction.ts, examples/typescript/simple_transfer.ts, examples/typescript/swap.ts, examples/typescript/transfer_coin.ts, examples/typescript/tsconfig.json, examples/typescript/your_coin.ts, examples/typescript/your_fungible_asset.ts
Example:
Using `undefined` as an index will not compile when using typescript strictly
```ts
// Error: if process.env.APTOS_NETWORK is undefined, this will fail when strict because 
// it does not allow you to use an undefined type to index values
NetworkToNetworkName[process.env.APTOS_NETWORK];
```
In javascript however, `undefined` will convert to a string `undefined`
```js
// Passes: if process.env.APTOS_NETWORK is undefined, it will pass in "undefined" as an index to NetworkToNetworkName
NetworkToNetworkName[process.env.APTOS_NETWORK];
```
Thus, if you have a key in `NetworkToNetworkName` called `"undefined"`, it will unintentionally use that key / value pair
Build passes
=> Typescript strict

src/internal/fungibleAsset.ts
got the error of 
```
Error: Type argument count mismatch, expected 0, received 1
at Tn (/Users/angiehuang/aptos-ts-sdk/dist/common/index.js:426:40395)
at Ti (/Users/angiehuang/aptos-ts-sdk/dist/common/index.js:426:46212)
at A (/Users/angiehuang/aptos-ts-sdk/dist/common/index.js:426:45888)
at fs (/Users/angiehuang/aptos-ts-sdk/dist/common/index.js:426:66253)
at zt.transferFungibleAsset (/Users/angiehuang/aptos-ts-sdk/dist/common/index.js:426:67560)
at X.o.value (/Users/angiehuang/aptos-ts-sdk/dist/common/index.js:426:88905)
at main (/Users/angiehuang/aptos-ts-sdk/examples/typescript/your_fungible_asset.ts:209:59)
```
when running `pnpm run your_fungible_asset`
run `pnpm run your_fungible_asset` again and make sure it works
=> fix your first fungible asset example

CHANGELOG.md, src/transactions/transactionBuilder/transactionBuilder.ts
Partner is facing this issue when they are trying to integrate their wallet code with the new wallet standard. We had past issues with using `instanceOf` (see https://github.com/aptos-labs/aptos-ts-sdk/pull/380 )
tests are passing
=> Remove `instanceOf` usage when generating signing message

CHANGELOG.md, src/api/aptos.ts, src/api/general.ts, src/api/table.ts, src/internal/account.ts, src/internal/general.ts, src/internal/queries/currentTokenOwnershipFieldsFragment.graphql, src/internal/queries/getTableItemsData.graphql, src/internal/queries/getTableItemsMetadata.graphql, src/internal/table.ts, src/types/generated/operations.ts, src/types/generated/queries.ts, src/types/generated/types.ts, src/types/indexer.ts, tests/e2e/api/account.test.ts, tests/e2e/api/general.test.ts, tests/e2e/api/table.test.ts
This PR
1. Adds `decimal` prop back to `current_token_ownerships_v2.current_token_data` response
2. Solves https://github.com/aptos-labs/aptos-ts-sdk/issues/376 , by adding 2 new `table` related queries - `getTableItemsData` and `getTableItemsMetadata`.
Currently, PFN doesnt return the table item data or metadata (i.e `data` field is always `null`, see https://fullnode.mainnet.aptoslabs.com/v1/transactions/by_version/563060087 ) and Indexer doesnt have a join query that can return all the data in one response.
This PR adds the 2 different Indexer queries where one can fetch the decoded table item data.
For example, consider https://explorer.aptoslabs.com/txn/563060087/changes?network=mainnet (index 5) [Indexer](https://cloud.hasura.io/public/graphiql?endpoint=https%3A%2F%2Findexer.mainnet. …
=> Introduce `table` function API. Add `getTableItemsData` and `getTableItemsMetadata` queries

CHANGELOG.md, src/transactions/typeTag/parser.ts, tests/unit/typeTagParser.test.ts
1. This now trims excess spaces out from around tags
2. This now allows uppercase primitive types (not struct names)
3. This now allows nested references on all types
4. Properly handles commas and spaces in generics
5. Tests generics with primitive types
The test coverage for this area is near 100% now
=> [typeTag] Add remaining coverage for type tag parser

CHANGELOG.md, src/transactions/transactionBuilder/remoteAbi.ts, src/transactions/transactionBuilder/transactionBuilder.ts, src/transactions/types.ts, tests/e2e/transaction/helper.ts, tests/e2e/transaction/transactionBuilder.test.ts, tests/move/transfer/sources/script_coin_transfer.move
Allows strings to be inputted as type arguments for scripts, similar to entry functions
E2E tests with type tags and with strings
=> [scripts] auto convert string type tags

CHANGELOG.md, src/api/general.ts, src/internal/general.ts, src/internal/transaction.ts, tests/e2e/api/general.test.ts, tests/e2e/api/transaction.test.ts
Additionally, this breakingly changes the block APIs to be under transaction rather than general, due to a circular dependency.
I tested this live against Mainnet, which has over 100 transactions per block.  This helped me work out some of the edge conditions of off by 1.
=> [block] Change block APIs to fetch all transactions in the block

CHANGELOG.md, src/cli/move.ts
When there is more than 1 named addresses, they need to surrounded by "".
Here's the cli version
```
OUTPUT=$(aptos move create-object-and-publish-package \
--skip-fetch-latest-git-deps \
--package-dir move \
--address-name launchpad_addr \
--named-addresses "launchpad_addr=$PUBLISHER_ADDR,minter=$MINTER_ADDR"\
--profile $PUBLISHER_PROFILE \
--assume-yes)
```
=> fix named address in cli

CHANGELOG.md, src/bcs/serializable/moveStructs.ts, src/transactions/transactionBuilder/helpers.ts, src/transactions/transactionBuilder/remoteAbi.ts, tests/e2e/transaction/transactionArguments.test.ts
- Fixes `MoveVector.U8([])` to not error out
- Adds testing for backwards compatible cases
- Adds better handling around `""` for a number input type
See unit tests
=> [remoteAbi] Fixes some issues in the type tag parsing

examples/typescript/keyless_mainnet.ts, examples/typescript/package.json
Main net doesn't have a faucet, so adding an example for Keyless that works on Mainnet which includes directions for instantiating the account
```
pnpm i
pnpm build
cd examples/typescript
pnpm keyless_mainnet
```
=> Add example for keyless mainnet

src/api/general.ts, src/internal/view.ts, src/transactions/types.ts, tests/e2e/api/general.test.ts
This keeps the original behavior from the Legacy SDK but as a different function on the SDK.
See unit tests
=> [api] Add viewJson as a way to migrate from the legacy SDK

CHANGELOG.md, src/api/account.ts, src/api/aptos.ts, src/api/object.ts, src/internal/account.ts, src/internal/object.ts, src/internal/queries/getObjectData.graphql, src/types/generated/operations.ts, src/types/generated/queries.ts, src/types/indexer.ts, src/utils/const.ts, tests/e2e/api/object.test.ts
- Introduce `AptosObject` API for all Object queries
- Add `getObjectData` API function to fetch an object data by the object address
-
=> Introduce `AptosObject`  API for all Object queries

CHANGELOG.md, src/api/digitalAsset.ts, src/api/object.ts, src/internal/digitalAsset.ts, src/internal/object.ts, src/internal/queries/getCollectionData.graphql, src/types/generated/operations.ts, src/types/generated/queries.ts, src/types/generated/types.ts, tests/e2e/api/digitalAsset.test.ts, tests/e2e/api/object.test.ts
- Add `getCollectionDataByCreatorAddressAndCollectionName` and `getCollectionDataByCreatorAddress` API queries
- Add `PaginationArgs` argument to `getCollectionDataByCollectionId` API query
- Mark `getCollectionData` API query as `@deprecated`
- Rename `getObjectData` query to `getObjectDataByObjectAddress` (hasn't release yet)
testa are passing - can see no breaking changes
=> Add digital asset api queries and modify object api query

CHANGELOG.md, src/internal/account.ts
Amount isn't necessary here, so it's been removed
This was reported https://github.com/aptos-labs/aptos-ts-sdk/issues/434
Tested manually with that code associated there.
=> [fix] getAccountCollectionsWithOwnedTokens to remove amount

CONTRIBUTING.md, package.json
This PR adds a `publish` command to run with `pnpm run publish` to make sure we first build the package and then publish it to NPM
=> Add a publish command

CHANGELOG.md, src/api/account.ts, src/core/accountAddress.ts, src/internal/account.ts
For migrated coins, they need to query both the address and the coin type associated.
=> [fungibleAssets] Ensure query for coin balances uses correct query

CHANGELOG.md, src/internal/ans.ts, src/internal/queries/ansTokenFragment.graphql, src/types/generated/operations.ts, src/types/generated/queries.ts, src/types/generated/types.ts, tests/e2e/ans/ans.test.ts
[An issue was raised for the ANS api](https://github.com/aptos-labs/aptos-names/pull/313). This PR brings the logic from that fix the the SDK. 
See the test plan for the linked PR.
=> Removes use of `is_active` for ANS queries

CHANGELOG.md, src/account/KeylessAccount.ts, src/core/crypto/ephemeral.ts, tests/e2e/api/keyless.test.ts
This adds very basic signature verification in order to enable sign and verify for the wallet adapter.  This implementation is incomplete as it only checks the ephemeral signature.  
Full verification of the proof and training wheels will be done later as it requires querying the chain and the right bn254 library to deserialize the g1/g2 points of the VK.
Added e2e test
=> Implement a base version of verifySignature for KeylessAccounts

CHANGELOG.md, src/client/core.ts, src/client/types.ts, tests/unit/__snapshots__/client.test.ts.snap, tests/unit/client.test.ts
This improves the error message handling in the SDK. Previously we would receive `AptosApiError: [object Object]` and other non-descriptive errors in some cases. This came up in debugging the keyless e2e tests specifically.
=> ensure that errors have a meaningful message

CHANGELOG.md, src/core/accountAddress.ts, src/core/crypto/ed25519.ts, src/core/crypto/keyless.ts, src/core/crypto/secp256k1.ts, src/core/crypto/singleKey.ts, src/transactions/transactionBuilder/transactionBuilder.ts, tests/unit/ed25519.test.ts, tests/unit/publicKey.test.ts
The usage of `instanceof` keeps causing a lot of problem, specifically when using the TS sdk from different bundles.
Sometimes this is due to misconfiguration, some other times there's no way around it (e.g. injected wallet plugins).
This PR attempts to remove the usage of `instanceof` from all flows were inputs might come from different bundles:
- When using `Account.from` with an instance of `AccountAddress`
- When verifying a signature using an instance of `Signature`
- When simulating a transaction using an instance of `PublicKey`
CI, as well as manually testing Wapal that is currently unable to integrate with AptosConnect because of the above problem.
=> [core] Remove `instanceof` where input might come from other bundle

CHANGELOG.md, examples/typescript/local_node.ts, src/cli/localNode.ts
Change the `stop()` function on `LocalNode` to return a `Promise` so we can wait for the processes to be killed
=> Change `LocalNode stop()` function to return a Promise

CHANGELOG.md, examples/typescript/local_node.ts, src/cli/move.ts
Introduce `buildPublishPayload` CLI function to build a publication transaction payload and store it in a JSON output file
=> Introduce a `buildPublishPayload` function

CHANGELOG.md, src/transactions/transactionBuilder/transactionBuilder.ts
Regression in this PR https://github.com/aptos-labs/aptos-ts-sdk/commit/cb7e8bb8c6242eca6d488bb361bdd483dc1a421d#diff-97f79e1249bb5dfd1fc52b16da86fbcd1d517e8897c7cc0d70c79e73c61ecf3cR456 left out Keyless signatures which broke simulations leading to underpriced transactions.
Tested simulation in custom builds
N/A
=> [keyless] Add KeylessSignature when simulating KeylessPublicKey

package.json, pnpm-lock.yaml, src/plugins/assetUploader/irys.ts, src/plugins/assetUploader/types.ts
1. irys `0.29.0` takes in new interface `url` which points to either `https://arweave.devnet.irys.xyz` or `https://arweave.mainnet.irys.xyz`
2. verified asset uploading was fixed on the irys side cuz our sdk api changed on `generateSigningMessage` so irys upgraded to use `generateSigningMessageForTransaction` instead
successful txn hash: `0xe6ec1ca38679a2412dd4eb575b2f219fc813e550c92558035f9c14fd8d8cfbe8`
=> upgrade to irys 0.29.0

CHANGELOG.md, cucumber.js, package.json, pnpm-lock.yaml, src/bcs/deserializer.ts, tests/features/bcs_deserialization.feature, tests/features/bcs_serialization.feature, tests/step-definitions/bcs.steps.mts
This is a prototype for cross SDK specifications.  It points out some interesting differences between SDKs even just for BCS.  We'll need to go and sit down and write proper specifications that cover the behavior we want.
This is a mirror of the Go SDK spec PR https://github.com/aptos-labs/aptos-go-sdk/pull/78 with the same exact specification!
I got everything running with the below command.  We will need to probably run it in CI, but until we settle on actual specs, I do not want to run them in CI for the time being.
```bash
pnpm _spec
> @aptos-labs/ts-sdk@1.26.0 _spec /opt/git/typescript-sdk
> ./node_modules/.bin/cucumber-js -p default
(node:47604) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was …
```
=> [bcs] Add BCS Spec

tests/e2e/transaction/helper.ts, tests/e2e/transaction/transactionSimulation.test.ts
The multisig simulation test fails with a vm_status: 'ACCOUNT_NOT_MULTISIG' error because the address used in the test is not associated with a multisig account. Additionally, the multisig transaction has not been submitted on-chain.
This update resolves the issue by properly setting up the multisig simulation test environment:
* Creating and using a multisig account.
* Creating a multisig transaction before running the simulation. 
Two helper functions, `createAndFundMultisigAccount` and `createMultisigTransaction`, are introduced. These functions can also be helpful in the future.
unit tests
This resolves https://github.com/aptos-labs/aptos-ts-sdk/issues/505.
=> Fixed the multisig simulation test failure

tests/e2e/transaction/transactionSimulation.test.ts
This PR fixes a typo by correcting "recieverAccounts" to "receiverAccounts" in `transactionSimulation.test.ts`.
CI test
N.A.
=> Correct typo in variable name

CHANGELOG.md, src/core/crypto/utils.ts
Fixes non-hex message signing on browser platforms
Resolves: https://github.com/aptos-labs/aptos-ts-sdk/issues/520
=> [fix] Allow signing non-hex messages on all platforms

CHANGELOG.md, src/api/account.ts, src/internal/account.ts, tests/e2e/api/account.test.ts
Uses a view function rather than the indexer to get more up to date balance info / handle balances more accurately for migrated coins.
Resolves https://github.com/aptos-labs/aptos-ts-sdk/issues/459
=> [coin/fa] Use view function rather than indexer to get current balances

src/types/index.ts
TS SDK counterpart to https://github.com/aptos-labs/aptos-core/pull/14246.
We can't release this yet, the `is_event` field has only been released to devnet and testnet so far.
I see there are no tests for `is_native` so idk if we normally test these fields, given they're really just served verbatim from the API. Happy to add tests if requested.
- https://github.com/aptos-labs/aptos-core/pull/14246
=> Add is_event to MoveStruct

CHANGELOG.md, examples/typescript/simple_sponsored_transaction.ts, src/account/AbstractKeylessAccount.ts, src/account/FederatedKeylessAccount.ts, src/account/KeylessAccount.ts, src/account/MultiKeyAccount.ts, src/account/index.ts, src/api/transaction.ts, src/internal/transactionSubmission.ts, tests/e2e/transaction/transactionSubmission.test.ts
This simplifies the fee payer APIs by reducing the steps needed to submit such a transaction while still maintaining support for remote signing.
Now the txn may be submitted either on the fee payer side or the sender side.
This also improves the keyless experience as proofs may be fetched asynchronously, in those cases since submission is an async function where we can await the proof fetch.
Tested via sponsored txn example.
More tests in progress
=> Improve fee payer txn submission APIs

src/client/core.ts, src/transactions/transactionBuilder/transactionBuilder.ts
Exclamations can cause unexpected failures, so this just checks for validity of any usages of exclamations, and throws an error (or passes a default value), when not present
=> [refactor] Remove remaining exclamations asserting non-null

src/core/crypto/hdKey.ts
Fixes [https://github.com/aptos-labs/aptos-ts-sdk/security/code-scanning/2](https://github.com/aptos-labs/aptos-ts-sdk/security/code-scanning/2)
To fix the problem, we need to ensure that all occurrences of the apostrophe character are removed from the input string. The best way to achieve this is by using a regular expression with the global flag (`g`). This will ensure that every instance of the apostrophe character is replaced, not just the first one.
- Modify the `removeApostrophes` function to use a regular expression with the global flag.
- No additional imports or dependencies are required for this change.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix code scanning alert no. 2: Incomplete string escaping or encoding

CHANGELOG.md, src/transactions/typeTag/index.ts, tests/unit/typeTag.test.ts
We have an isPrimitive function in `parser.ts` but it is not exported and only operates on strings. It'd be nicer to have the function on `TypeTag` directly.
Note that we can't do `this.isSigner() | this.isAddress()` etc because the typechecker (perhaps erroneously) makes the type more specific due to the first check, so the rest of the checks fail typechecking.
See updated unit tests.
N/A
=> Add isPrimitive function to TypeTag

src/api/account.ts
Following https://github.com/aptos-labs/aptos-ts-sdk/pull/519, `getAccountCoinAmount` API function does not use Indexer to fetch the data and therefore `minimumLedgerVersion` is not needed.
We keep it as a function argument to not break projects, but it is a bit confusing as devs think this function still uses Indexer
=> Log `minimumLedgerVersion` is not used anymore warning

README.md, src/account/KeylessAccount.ts, src/bcs/serializable/moveStructs.ts, src/core/accountAddress.ts, src/core/crypto/ed25519.ts, src/core/crypto/hdKey.ts, src/core/crypto/privateKey.ts, src/core/crypto/secp256k1.ts
These docs updates remove things that don't apply to TSDoc, are duplicated, or just don't match existing information.
Running the generate docs command spits out most of these warnings, so I've gotten rid of a good amount of them.
=> [docs] Fix docs tags that don't match tags supported in TSDoc

.gitignore, CHANGELOG.md, examples/typescript-esm/multisig_v2.ts, src/api/transactionSubmission/helpers.ts, src/api/transactionSubmission/simulate.ts, src/internal/transactionSubmission.ts, src/transactions/authenticator/account.ts, src/transactions/transactionBuilder/transactionBuilder.ts, src/transactions/types.ts, src/types/types.ts, tests/e2e/transaction/transactionSimulation.test.ts, tests/e2e/transaction/transactionSubmission.test.ts
This PR updates the TypeScript SDK to support the simulation enhancement AIP: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-92.md.
Key Changes:
Simulation API Update: Allows users to simulate transactions without providing public keys by updating simulateTransaction to accept `PublicKey | null` instead of `PublicKey`. If null is provided, `NoAccountAuthenticator` is used as an authenticator. This new authenticator variant is supported by the Aptos VM as per [this PR](https://github.com/aptos-labs/aptos-core/pull/13714).
Multisig V2 Example Update: The multisig v2 example (multisig_v2.ts) is updated to reflect the change in the multisig transaction simulation behavior. To pre-check the multisig payload before creation, an entry function payload simulation with the multisig …
=> Add the `NoAccountAuthenticator` variant

CHANGELOG.md, examples/typescript/local_node.ts, src/cli/move.ts
=> Add `gasProfile()` method to run Move gas profiling

src/core/crypto/secp256k1.ts, tests/unit/secp256k1.test.ts
Support compressed public keys for secp256k1 natively in the SDK.
Looks like originally it only supported uncompressed keys, which may not be given to users.
Check out the new test for how we test compression.
=> [secp256k1] Support inputed compressed public keys

pnpm-lock.yaml, src/api/aptos.ts, src/api/permissions.ts, src/internal/permissions.ts, src/types/permissions.ts, tests/e2e/transaction/delegationPermissions.test.ts
big thanks to @kaw2k for the help + stubs
Best Practice Questions:
- Currently types are living under `internal/Permissions.ts`, should they be moved to `api/...ts`?
- Based on the context, types should likely move to api/ since they are part of the public interface
- This matches the pattern seen in api/permissions.ts which exposes the Permission types
- Should we remove the factories for each permissions or keep both types and factories?
- Factories don't provide much value beyond type construction
- Tests show direct object construction is just as clear
- Consider deprecating factories in favor of just types
Points of Interest:
- Issue with returning arrays in `grantPermission`:
- NFT permissions can have multiple capabilities (transfer, mutate)
- Current workaround is handling each …
=> Permissioned Accounts

examples/typescript/keyless.ts, src/api/permissions.ts, src/index.ts, src/internal/permissions.ts, src/types/index.ts, src/types/permissions.ts, tests/e2e/transaction/delegationPermissions.test.ts
There will need to be more work here, for example I didn't convert the revoke permissions to be a serializable class. Looking to get feedback. 
Tests pass 
Base PR #596
=> Converts permissions to a serializable class

src/api/transactionSubmission/build.ts, tests/e2e/transaction/transactionSubmission.test.ts
- Added the default FeePayer address (`AccountAddress.ZERO`) when the `withFeePayer` parameter is `true` to resolve the `not a FeePayer transaction` issue while executing FeePayer transactions with Script Composer.
- Added tests to verify that FeePayer transactions are correctly processed and handled in the updated logic.
=> Fix: Add default FeePayer address for sponsored transactions in Script Composer

CHANGELOG.md, src/api/account.ts, src/client/get.ts, src/internal/account.ts, tests/e2e/api/account.test.ts
Resolves https://github.com/aptos-labs/aptos-ts-sdk/issues/576
Added pagination tests for both calls
=> [account] Fix pagination on AccountModules and AccountResources

CHANGELOG.md, README.md, examples/typescript/keyless_mainnet.ts, tests/e2e/api/keyless.test.ts
The _old_ code did not properly wait for the testing account to be funded when the account did not exist. (Not sure if it correctly handled the account existing but with balance 0.)
The **new** code should now properly handle both cases: i.e., the `getAccountAPTAmount ` function returning zero for both a non-existent account and an existing account.
We now wait in a `while` loop until the account has enough funds to pay the gas and cover the transferred amount (even though paying to self).
(Related to https://github.com/aptos-labs/aptos-ts-sdk/pull/618 which properly documents the behavior of the `getAccountAPTAmount` function.)
This is an end-to-end test. So I manually-tested the test, lol.
None.
=> fix keyless end-to-end mainnet test to actually wait for funded account

CHANGELOG.md, src/transactions/transactionBuilder/remoteAbi.ts, tests/unit/remoteAbi.test.ts
In a Web env, arguments passing into the sdk are strings, so if we pass arguments as `[1,2,3]`, the web will convert it into `"[1,2,3]"`.
This PR adds support to convert the array as string argument to an array, so then we can convert it to a BSC argument.
This is already semi-supported by the Explorer, adding it to the SDK for a more general solution
- Added a new test
[Simulation](http://localhost:3000/manage/transactions/simulation?network=testnet&data=%7B%22version%22%3A%226613599144%22%2C%22hash%22%3A%220x0c824b50ca003ba147d4da5626b77167c71440f7e1b52fb0807f59060ec5c139%22%2C%22state_change_hash%22%3A%220xdefb59588f3c4b798236f295d33da4f9d8dfad7063917205feaa36650734bf5f%22%2C%22event_root_hash%22%3A%220x6c3b14438f35843f65a29efca454375bd623e4e8bf8ca4007803f7cc8fab251e%22%2C%22state_check …
=> Add support for vector arguments passing in as strings

README.md
Fix link to `index.global.js` file (corrected closing `</script>` tag)
Improve readability and consistency of some sentences
Update minor phrases for better understanding
=> Fix link to `index.global.js` file (corrected closing `</script>` tag)

CHANGELOG.md, src/transactions/transactionBuilder/transactionBuilder.ts
Previously multikey just used null ed25519 signatures.  This gave too optimistic gasEstimates which would lead to MAX_GAS_UNITS_BELOW_MIN_TRANSACTION_GAS_UNITS error.  It is better to be pessimistic within reason.
TODO - only include N signatures where N = signaturesRequired.  Right now we have N = num of pub keys
=> For multiKey simulation - use signature of same type

CHANGELOG.md, src/transactions/scriptComposer/index.ts
Fix scriptComposer addBatchedCalls more typeArguments error
<recursive use of an object detected which would lead to unsafe aliasing in rust>
=> [scriptComposer]fix object detected in rust

CHANGELOG.md, src/api/account.ts, src/client/get.ts, src/internal/account.ts, src/internal/utils/utils.ts, src/types/types.ts, tests/e2e/api/account.test.ts
Right now, you can just request a very long page, but that's really not useful for explorers and other things.  Ideally, it should get all, and not just query up to some amount.  May consider removing default page sizes of default APIs in the future.
Resolves https://github.com/aptos-labs/aptos-ts-sdk/issues/665
See new unit tests around pagination testing.
=> [paginaton] Fix cursor pagination, add by page APIs

CHANGELOG.md, src/core/accountAddress.ts, src/utils/helpers.ts, tests/unit/helpers.test.ts
add a helper function `pairedFaMetadataAddress` to return the paired fa address for even non-standard coin type string.
unit test.
=> [ts-sdk] add a helper function to return the paired FA address

CHANGELOG.md, src/core/crypto/publicKey.ts
This allows for simpler implementation of publicKeys, for example EIP1193DerivedPublicKey in the wallet adapter
=> Add a default implementation of verifySignatureAsync

examples/typescript/package.json
https://github.com/aptos-labs/aptos-ts-sdk/pull/624 accidentally broke CI by removing an example but not removing it from `pnpm test` for the TS examples.
See CI.
- N/A
=> Remove view_bcs script from examples to fix CI following #624

CHANGELOG.md, src/core/crypto/singleKey.ts
=> Define the return type for `toUint8Array()` in the `SingleKey.ts` file to not break `tsc` build

CHANGELOG.md, src/api/account.ts, src/internal/account.ts, tests/e2e/api/account.test.ts
Note that most wallets supported the legacy key, so we are putting that as the default.  But, this needs to be deprecated as it is no longer useful when all accounts are listed as "created"
=> [account] Fix derive account from private key on chain

confidential-assets/package.json, confidential-assets/pnpm-lock.yaml, confidential-assets/src/confidentialAsset.ts, confidential-assets/src/consts.ts, confidential-assets/tests/helpers/index.ts
In this PR I make it possible to set the confidential assets module address as part of the `ConfidentialAsset` class' constructor.
Also the default value wasn't correct for any network, now it uses the correct value for devnet, the only place we deploy the module automatically right now.
```
cd confidential-assets
pnpm test
```
=> [confidential-assets] Make setting module address a little more ergonomic

confidential-assets/package.json, confidential-assets/src/confidentialAsset.ts
The SDK makes some invalid assumptions around fee payers, it is valid to set `withFeePayer` but not set a `feePayerAddress`.
CI. I also tested manually as part of https://github.com/aptos-labs/confidential-payments-example.
=> Fix incorrect assumption about withFeePayer

confidential-assets/package.json, confidential-assets/src/confidentialAsset.ts
The module address provided in the constructor wasn't being passed through properly. To prevent issues like this in the future, the static methods now take the module address as a required argument. This way the dev knows for sure that they're passing in the default if they want.
Tested manually as part of https://github.com/aptos-labs/confidential-payments-example.
=> [confidential-assets] Use provided module address truly everywhere

CHANGELOG.md, src/api/aptosConfig.ts
Adds a warning if users don't set their network appropriately as it adds extra network calls.
=> [client] Add warning if setting a custom network without a chain id

CHANGELOG.md, examples/typescript/custom_client.ts, package.json, pnpm-lock.yaml
This PR updates `@aptos-labs/aptos-client` to version `2.0.0` which removes the dependency on `axios` in favor of the native `fetch` in the browser.
Ran tests locally
Tested locally in wallet adapter demo, Aptos Build, and Explorer
=> Update aptos-client to v2.0.0

confidential-assets/package.json, confidential-assets/src/confidentialAmount.ts, confidential-assets/src/confidentialAsset.ts
Right now user code needs to keep track of whether `amountEncrypted` is undefined or not. This field is ultimately intended to be a cache to prevent having to recompute the data, so let's protect it behind a function that will compute the value if needed on demand.
todo
=> Fix potential for unsafe access with amountEncrypted

confidential-assets/src/confidentialAmount.ts, confidential-assets/src/confidentialAsset.ts, confidential-assets/src/confidentialKeyRotation.ts, confidential-assets/src/confidentialNormalization.ts, confidential-assets/src/confidentialTransfer.ts, confidential-assets/src/confidentialWithdraw.ts, confidential-assets/tests/e2e/confidentialCoin.test.ts, confidential-assets/tests/units/api/checkBalances.test.ts, confidential-assets/tests/units/api/negativeNormalize.test.ts, confidential-assets/tests/units/api/negativeTransfer.test.ts, confidential-assets/tests/units/api/negativeWithdraw.test.ts, confidential-assets/tests/units/api/normalize.test.ts, confidential-assets/tests/units/api/safelyRotateKey.test.ts, confidential-assets/tests/units/api/transfer.test.ts, confidential-assets/tests/units/api/transferWithAuditor.test.ts, confidential-assets/tests/units/api/withdraw.test.ts, confidential-assets/tests/units/confidentialProofs.test.ts, confidential-assets/tests/units/kangaroo-decryption.test.ts
The previous PR (https://github.com/aptos-labs/aptos-ts-sdk/pull/706) was incomplete, this PR updates the rest of the code to use the new function. There is no need for external callers to call `encrypt` manually anymore, we do it internally when needed.
See that `pnpm build` passes now.
=> Correctly use new getAmountEncrypted function

CHANGELOG.md, src/api/aptosConfig.ts, src/transactions/transactionBuilder/transactionBuilder.ts, src/types/types.ts
This allows for the dev to change the default without setting it in every call
=> Make default gas and expiry time configurable at client construction

CHANGELOG.md, examples/typescript/package.json, examples/typescript/pnpm-lock.yaml, examples/typescript/simple_turbo_transfer.ts, src/api/transactionSubmission/build.ts, src/transactions/instances/transactionPayload.ts, src/transactions/management/transactionWorker.ts, src/transactions/transactionBuilder/transactionBuilder.ts, src/transactions/types.ts, src/types/types.ts, tests/e2e/transaction/transactionSubmission.test.ts, tests/unit/transactionPayload.test.ts
This enables orderless transactions to be submitted.  Instead of submitting account sequence number, users would submit the replayProtectionNonce
=> [txns] Add support for orderless transactions

CHANGELOG.md, src/api/transactionSubmission/helpers.ts, src/api/transactionSubmission/submit.ts
In this PR we skip `validateFeePayerDataOnSubmission` if a custom txn submitter is provided. The validation is invalid in the case where your custom txn submitter sends the txn to a gas station, there is no need to set the fee payer authenticator yet client side in this scenario.
We also change it from a decorator to just a normal function. The decorator was neat but also hard to work with for this and untyped, the new approach is safer. The function is not exported by the SDK so this doesn't qualify as a breaking change.
CI
=> Skip validateFeePayerDataOnSubmission if a custom txn submitter is provided

.github/workflows/run-build.yaml, .github/workflows/run-check-version.yaml, .github/workflows/run-confidential-assets-tests.yaml, .github/workflows/run-examples.yaml, .github/workflows/run-fmt.yaml, .github/workflows/run-lint.yaml, .github/workflows/run-tests.yaml
Node 24 compatibility: switch all jobs to actions/checkout@v5. Requires runner v2.327.1+. Pure maintenance, behavior unchanged.
Ref: https://github.com/actions/checkout/releases/tag/v5.0.0
=> ci: bump actions/checkout to v5
